import {
  automations,
  botCallInsights,
  botLeadWorkflows,
  botLanguageRules,
  calendarEvents,
  contactRelationships,
  contactTimeline,
  contacts,
  consents,
  conversations,
  crmBotConversations,
  crmBots,
  crmBotTools,
  customerWorkspaceAccess,
  deals,
  funnelSteps,
  funnels,
  knowledgeBase,
  leadSequenceEvents,
  leadSequences,
  leads,
  newsletterAutomations,
  newsletterCampaigns,
  newsletterDeliverability,
  newsletterSegments,
  newsletterSuppressions,
  newsletterTemplates,
  organizations,
  pipeline,
  propertyBuildings,
  propertyReservations,
  propertyUnits,
  projects,
  sellerListings,
  tasks,
  users,
  workspace,
} from "@/lib/crm-data";

export const crmDataSource = "mock" as const;

export const crmSnapshot = {
  automations,
  botCallInsights,
  botLeadWorkflows,
  botLanguageRules,
  calendarEvents,
  contactRelationships,
  contactTimeline,
  contacts,
  consents,
  conversations,
  crmBotConversations,
  crmBots,
  crmBotTools,
  customerWorkspaceAccess,
  deals,
  funnelSteps,
  funnels,
  knowledgeBase,
  leadSequenceEvents,
  leadSequences,
  leads,
  newsletterAutomations,
  newsletterCampaigns,
  newsletterDeliverability,
  newsletterSegments,
  newsletterSuppressions,
  newsletterTemplates,
  organizations,
  pipeline,
  propertyBuildings,
  propertyReservations,
  propertyUnits,
  projects,
  sellerListings,
  tasks,
  users,
  workspace,
};

export type CrmSnapshot = typeof crmSnapshot;

export function getCrmSnapshot(): CrmSnapshot {
  return crmSnapshot;
}

export {
  automations,
  botCallInsights,
  botLeadWorkflows,
  botLanguageRules,
  calendarEvents,
  contactRelationships,
  contactTimeline,
  contacts,
  consents,
  conversations,
  crmBotConversations,
  crmBots,
  crmBotTools,
  customerWorkspaceAccess,
  deals,
  funnelSteps,
  funnels,
  knowledgeBase,
  leadSequenceEvents,
  leadSequences,
  leads,
  newsletterAutomations,
  newsletterCampaigns,
  newsletterDeliverability,
  newsletterSegments,
  newsletterSuppressions,
  newsletterTemplates,
  organizations,
  pipeline,
  propertyBuildings,
  propertyReservations,
  propertyUnits,
  projects,
  sellerListings,
  tasks,
  users,
  workspace,
};
