import { createHash } from 'node:crypto';
import type { AppSession } from './auth/session';
import { getRolePermissions } from './auth/permissions';
import { getProductRoleCapabilities } from './product-model';
import { assertProjectGrant, CrmCommandError, crmPayloadDigest, withCrmRead, type TenantTransactionOptions } from './crm-command';
import { queryAuthenticationRows } from './db/tenant-client';

export const CRM_QA_WRITE_CONTRACT_VERSION='crm-qa-write-v1';
type Principal={id:string;workspace_id:string;actor_user_id:string;tenant_alias:string;agent_id:string;scopes:string[];data_context:string;data_classification:string;purpose:string};
type Binding={source_id:string;project_id:string;entity:string;data_context:string;data_classification:string;domain:string;purpose:string};
type Envelope={contractVersion:typeof CRM_QA_WRITE_CONTRACT_VERSION;environment:'preview';synthetic:true;operation:'Revalidate'|'CreateActivity'|'CleanupActivity';tenantId:string;resourceId:string;actorId:'executive';correlationId:string;idempotencyKey:string;activityId:string;approvalReference:string;actionHash:string;payloadHash:string;auditReference:string;expectedVersion:string;content:'SYNTHETIC: EVM-08C controlled QA activity'};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,sim=/^sim-[a-z0-9][a-z0-9:_-]{0,100}$/,hex=/^[a-f0-9]{64}$/;
function fail(code='CRM_NOT_ACCESSIBLE',status=403):never{throw new CrmCommandError(code,code,status);}
function parse(raw:unknown):Envelope{if(!raw||typeof raw!=='object'||Array.isArray(raw))return fail('INVALID_CRM_REQUEST',400);const p=raw as Record<string,unknown>,keys=['contractVersion','environment','synthetic','operation','tenantId','resourceId','actorId','correlationId','idempotencyKey','activityId','approvalReference','actionHash','payloadHash','auditReference','expectedVersion','content'];if(Object.keys(p).sort().join('|')!==keys.sort().join('|'))return fail('INVALID_CRM_REQUEST',400);if(p.contractVersion!==CRM_QA_WRITE_CONTRACT_VERSION||p.environment!=='preview'||p.synthetic!==true||!['Revalidate','CreateActivity','CleanupActivity'].includes(String(p.operation))||p.actorId!=='executive'||p.content!=='SYNTHETIC: EVM-08C controlled QA activity')return fail('INVALID_CRM_REQUEST',400);if(!sim.test(String(p.tenantId))||!sim.test(String(p.resourceId))||!sim.test(String(p.approvalReference))||!sim.test(String(p.auditReference))||!/^evm08c-[a-z0-9-]{8,100}$/.test(String(p.idempotencyKey))||!uuid.test(String(p.correlationId))||!uuid.test(String(p.activityId))||!hex.test(String(p.actionHash))||!hex.test(String(p.payloadHash))||!hex.test(String(p.expectedVersion)))return fail('INVALID_CRM_REQUEST',400);return p as Envelope;}
function errorResponse(error:unknown,correlationId?:string){let code='CRM_RESULT_UNKNOWN',status=503;if(error instanceof CrmCommandError){code=error.code;status=error.status;}return Response.json({contractVersion:CRM_QA_WRITE_CONTRACT_VERSION,code,correlationId:correlationId??null,retry:code==='CRM_RESULT_UNKNOWN'?'RECONCILE_ONLY':'NEVER'},{status,headers:{'Cache-Control':'no-store'}});}
export async function handleCrmQaWriteContract(request:Request,options:TenantTransactionOptions={}):Promise<Response>{let envelope:Envelope|undefined;try{
 if(process.env.VERCEL_ENV!=='preview'||process.env.VERCEL_TARGET_ENV==='production'||process.env.CRM_EVM08C_QA_WRITE_ENABLED!=='true')return fail();
 if(request.method!=='POST'||request.headers.has('cookie')||request.headers.has('origin'))return fail();const match=/^Bearer (qa-crm-v1\.[A-Za-z0-9_-]{43,128})$/.exec(request.headers.get('authorization')??'');if(!match)return fail('CRM_NOT_ACCESSIBLE',401);const credentialHash=createHash('sha256').update(match[1]).digest('hex');const principal=(await queryAuthenticationRows<Principal>('select * from crm_authenticate_service($1)',[credentialHash],options))[0];if(!principal)return fail('CRM_NOT_ACCESSIBLE',401);const text=await request.text();if(text.length>8192)return fail('INVALID_CRM_REQUEST',400);envelope=parse(JSON.parse(text));const r=envelope;if(r.tenantId!==principal.tenant_alias||r.actorId!==principal.agent_id||!principal.scopes.includes('crm.qa.activity.write'))return fail();
 const session:AppSession={authenticated:true,userId:principal.actor_user_id,workspaceId:principal.workspace_id,workspaceName:'Synthetic contract',name:'Synthetic service actor',email:'synthetic-service@example.invalid',role:'agent',productRole:'project_sales_member',permissions:getRolePermissions('agent'),productPermissions:getProductRoleCapabilities('project_sales_member'),source:'database'};
 const result=await withCrmRead(session,async(tx,fresh)=>{const locked=await tx.queryOne<Principal>('select * from crm_authenticate_service($1)',[credentialHash]);if(!locked||crmPayloadDigest(locked)!==crmPayloadDigest(principal))return fail();const binding=await tx.queryOne<Binding>('select source_id,project_id,entity,data_context,data_classification,domain,purpose from crm_service_resource_bindings where principal_id=$1 and workspace_id=$2 and resource_alias=$3',[principal.id,principal.workspace_id,r.resourceId]);if(!binding||binding.entity!=='Contact'||binding.data_context!==principal.data_context||binding.data_classification!==principal.data_classification||binding.domain!=='BUSINESS'||binding.purpose!==principal.purpose)return fail();await assertProjectGrant(tx,fresh,binding.project_id,r.operation!=='Revalidate');const audit=await tx.queryOne('select audit_alias from crm_service_audit_bindings where principal_id=$1 and workspace_id=$2 and audit_alias=$3 and resource_alias=$4 and request_hash=$5 and expires_at>clock_timestamp()',[principal.id,principal.workspace_id,r.auditReference,r.resourceId,crmPayloadDigest(r)]);if(!audit)return fail();const contact=await tx.queryOne<{id:string;version:number;name:string;updated_at:string|Date}>('select id,version,name,updated_at from contacts where id=$1::uuid and workspace_id=$2::uuid and project_id=$3::uuid for share',[binding.source_id,principal.workspace_id,binding.project_id]);if(!contact||!contact.name.startsWith('SYNTHETIC'))return fail();const updatedAt=contact.updated_at instanceof Date?contact.updated_at.toISOString():contact.updated_at,resourceVersion=crmPayloadDigest({id:contact.id,version:contact.version,updatedAt});if(resourceVersion!==r.expectedVersion)return fail('CRM_VERSION_CONFLICT',409);
  if(r.operation==='Revalidate')return{resourceVersion,available:true,sourceId:binding.source_id,projectId:binding.project_id};
  await tx.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[`evm08c:${principal.workspace_id}:${r.idempotencyKey}`]);const existing=await tx.queryOne<{id:string;request_hash:string;action_hash:string;cleaned_at:string|null}>('select id,request_hash,action_hash,cleaned_at from crm_evm08c_qa_activities where workspace_id=$1::uuid and idempotency_key=$2',[principal.workspace_id,r.idempotencyKey]);const requestHash=crmPayloadDigest(r);
  if(r.operation==='CreateActivity'){if(existing){if(existing.request_hash!==requestHash||existing.action_hash!==r.actionHash)return fail('CRM_IDEMPOTENCY_CONFLICT',409);return{activityId:existing.id,replayed:true,cleaned:existing.cleaned_at!==null};}await tx.execute(`insert into crm_evm08c_qa_activities(id,workspace_id,project_id,target_entity_id,principal_id,idempotency_key,request_hash,action_hash,payload_hash,content) values($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::uuid,$6,$7,$8,$9,$10)`,[r.activityId,principal.workspace_id,binding.project_id,binding.source_id,principal.id,r.idempotencyKey,requestHash,r.actionHash,r.payloadHash,r.content]);return{activityId:r.activityId,replayed:false,cleaned:false};}
  if(!existing||existing.action_hash!==r.actionHash)return fail('CRM_NOT_ACCESSIBLE',404);if(existing.cleaned_at===null)await tx.execute(`update crm_evm08c_qa_activities set content='SYNTHETIC: CLEANED EVM-08C QA activity',cleaned_at=clock_timestamp() where workspace_id=$1::uuid and id=$2::uuid and cleaned_at is null`,[principal.workspace_id,existing.id]);const cleaned=await tx.queryOne<{id:string;cleaned_at:string|null;content:string}>('select id,cleaned_at,content from crm_evm08c_qa_activities where workspace_id=$1::uuid and id=$2::uuid',[principal.workspace_id,existing.id]);return{activityId:existing.id,replayed:existing.cleaned_at!==null,cleaned:Boolean(cleaned?.cleaned_at),contentHash:crmPayloadDigest(cleaned?.content)};
 },options);return Response.json({contractVersion:CRM_QA_WRITE_CONTRACT_VERSION,correlationId:r.correlationId,idempotencyKey:r.idempotencyKey,...result},{headers:{'Cache-Control':'no-store'}});
 }catch(error){return errorResponse(error,envelope?.correlationId);}}
