import type {
  Automation,
  BotLanguageRule,
  CalendarEvent,
  ConsentRecord,
  Contact,
  ContactRelationship,
  ContactTimelineItem,
  Conversation,
  Deal,
  Funnel,
  FunnelStep,
  KnowledgeItem,
  Lead,
  SellerListing,
  NewsletterAutomation,
  NewsletterCampaign,
  NewsletterDeliverability,
  NewsletterSegment,
  NewsletterSuppression,
  NewsletterTemplate,
  Organization,
  PipelineStage,
  Project,
  Task,
  Workspace,
  WorkspaceUser,
} from "@/lib/crm-types";

export const workspace: Workspace = {
  id: "ws_novalure",
  name: "Novalure",
  plan: "Growth Workspace",
  activeProjects: 4,
  activeUsers: 12,
};

export const users: WorkspaceUser[] = [
  {
    id: "user_franz",
    workspaceId: workspace.id,
    name: "Franz",
    email: "franz@novalure.local",
    role: "owner",
    status: "active",
  },
  {
    id: "user_sales_graz",
    workspaceId: workspace.id,
    name: "Sales Graz",
    email: "graz@novalure.local",
    role: "agent",
    status: "active",
  },
];

export const navigation = [
  "Übersicht",
  "Lead Inbox",
  "Pipelines",
  "Kontakte",
  "Aufgaben",
  "Funnels",
  "Bots",
  "Wissen",
  "Newsletter",
  "Kalender",
];

export const projects: Project[] = [
  {
    id: "project_wohnpark_graz",
    workspaceId: workspace.id,
    name: "Wohnpark Graz",
    type: "Neubau Vertrieb",
    leads: 31,
    revenue: "1,82 Mio.",
    status: "Aktiv",
    defaultPipelineId: "pipeline_wohnpark_graz",
  },
  {
    id: "project_investment_wien",
    workspaceId: workspace.id,
    name: "Investment Wien",
    type: "Kapitalanlage",
    leads: 18,
    revenue: "940.000",
    status: "Skaliert",
    defaultPipelineId: "pipeline_investment_wien",
  },
  {
    id: "project_seller_linz",
    workspaceId: workspace.id,
    name: "Seller Leads Linz",
    type: "Eigentümer Funnel",
    leads: 44,
    revenue: "680.000",
    status: "Review",
    defaultPipelineId: "pipeline_seller_linz",
  },
  {
    id: "project_novalure_eu",
    workspaceId: workspace.id,
    name: "Novalure.eu",
    type: "Website Leads",
    leads: 22,
    revenue: "410.000",
    status: "Aktiv",
    defaultPipelineId: "pipeline_novalure_eu",
  },
];

export const organizations: Organization[] = [
  {
    id: "org_berger_family",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    name: "Familie Berger",
    type: "Privat",
    city: "Linz",
    ownerUserId: "user_franz",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Opportunity",
    lastActivityAt: "2026-05-11T09:22:00+02:00",
  },
  {
    id: "org_klein_household",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Haushalt Klein",
    type: "Privat",
    city: "Graz",
    ownerUserId: "user_sales_graz",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Lead",
    lastActivityAt: "2026-05-10T17:48:00+02:00",
  },
  {
    id: "org_hofer_invest",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Hofer Invest",
    type: "Investmentgesellschaft",
    city: "Wien",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Opportunity",
    lastActivityAt: "2026-05-11T08:13:00+02:00",
  },
  {
    id: "org_reiter_development",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Reiter Development",
    type: "Bauträger",
    domain: "reiter-development.example",
    city: "Graz",
    ownerUserId: "user_franz",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Partner",
    lastActivityAt: "2026-05-12T09:00:00+02:00",
  },
  {
    id: "org_markovic_household",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Haushalt Markovic",
    type: "Privat",
    city: "Graz",
    ownerUserId: "user_sales_graz",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Opportunity",
    lastActivityAt: "2026-05-11T12:40:00+02:00",
  },
  {
    id: "org_falkner_group",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    name: "Falkner GmbH",
    type: "Immobilienagentur",
    domain: "falkner.example",
    city: "Wien",
    ownerUserId: "user_franz",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Partner",
    lastActivityAt: "2026-05-10T11:15:00+02:00",
  },
];

export type Metric = {
  label: string;
  value: string;
  detail: string;
  tone: "emerald" | "blue" | "violet" | "amber";
};

export const metrics: Metric[] = [
  { label: "Neue Leads", value: "44", detail: "+12 diese Woche", tone: "emerald" },
  { label: "Gebuchte Termine", value: "9", detail: "Microsoft 365", tone: "blue" },
  { label: "Bot Gespräche", value: "126", detail: "WhatsApp und Instagram", tone: "violet" },
  { label: "Newsletter Opt-ins", value: "812", detail: "Resend Segmente", tone: "amber" },
];

export const contacts: Contact[] = [
  {
    id: "contact_anna_berger",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    organizationId: "org_berger_family",
    name: "Anna Berger",
    role: "Verkäufer",
    project: "Seller Leads Linz",
    source: "WhatsApp",
    intent: "Verkauf",
    consent: "Opt-in vorhanden",
    phone: "+43 660 000000",
  },
  {
    id: "contact_mira_klein",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    organizationId: "org_klein_household",
    name: "Mira Klein",
    role: "Käufer",
    project: "Wohnpark Graz",
    source: "Website Funnel",
    intent: "Besichtigung",
    consent: "Newsletter ja",
    email: "mira.klein@example.test",
  },
  {
    id: "contact_daniel_hofer",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    organizationId: "org_hofer_invest",
    name: "Daniel Hofer",
    role: "Investor",
    project: "Investment Wien",
    source: "Instagram",
    intent: "Kapitalanlage",
    consent: "Nur CRM",
  },
  {
    id: "contact_thomas_reiter",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    organizationId: "org_reiter_development",
    name: "Thomas Reiter",
    role: "Bauträger",
    project: "Wohnpark Graz",
    source: "Microsoft 365",
    intent: "Projektgespräch",
    consent: "Nur CRM",
  },
  {
    id: "contact_elena_markovic",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    organizationId: "org_markovic_household",
    name: "Elena Markovic",
    role: "Käufer",
    project: "Wohnpark Graz",
    source: "Website Funnel",
    intent: "Besichtigung",
    consent: "Newsletter ja",
    email: "elena.markovic@example.test",
  },
  {
    id: "contact_lukas_falkner",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    organizationId: "org_falkner_group",
    name: "Lukas Falkner",
    role: "Makler",
    project: "Novalure.eu",
    source: "Manual",
    intent: "Projektvertrieb",
    consent: "Nur CRM",
    email: "lukas@falkner.example",
  },
];

export const contactRelationships: ContactRelationship[] = [
  {
    id: "rel_anna_owner",
    workspaceId: workspace.id,
    contactId: "contact_anna_berger",
    organizationId: "org_berger_family",
    projectId: "project_seller_linz",
    role: "Eigentümer",
    influence: "hoch",
    isPrimary: true,
  },
  {
    id: "rel_mira_buyer",
    workspaceId: workspace.id,
    contactId: "contact_mira_klein",
    organizationId: "org_klein_household",
    projectId: "project_wohnpark_graz",
    role: "Käufer",
    influence: "hoch",
    isPrimary: true,
  },
  {
    id: "rel_daniel_investor",
    workspaceId: workspace.id,
    contactId: "contact_daniel_hofer",
    organizationId: "org_hofer_invest",
    projectId: "project_investment_wien",
    role: "Investor",
    influence: "hoch",
    isPrimary: true,
  },
  {
    id: "rel_thomas_developer",
    workspaceId: workspace.id,
    contactId: "contact_thomas_reiter",
    organizationId: "org_reiter_development",
    projectId: "project_wohnpark_graz",
    role: "Bauträger",
    influence: "mittel",
    isPrimary: true,
  },
];

export const leads: Lead[] = [
  {
    id: "lead_anna_berger",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    contactId: "contact_anna_berger",
    source: "willhaben",
    type: "Verkäufer",
    status: "Neu",
    score: 91,
    intent: "Verkaufsabsicht in 3 Monaten",
    nextAction: "Rückruf heute",
    receivedAt: "2026-05-11T09:20:00+02:00",
    slaDueAt: "2026-05-11T14:30:00+02:00",
    lastContactAt: "2026-04-03T09:22:00+02:00",
    nextContactAt: "2026-05-11T14:30:00+02:00",
    region: "Tirol",
    objectType: "Wohnung",
    rooms: 3,
    areaSqm: 84,
    hotStatus: true,
    sellerProfile: {
      address: "Innsbruck, Wilten",
      yearBuilt: 1998,
      marketValue: 420000,
      askingPrice: 445000,
      sellingReason: "Familienumzug",
      competingBroker: false,
      brokerContractStatus: "in Verhandlung",
      commissionRate: 3,
    },
    assignedToUserId: "user_franz",
  },
  {
    id: "lead_mira_klein",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_mira_klein",
    source: "Website",
    type: "Käufer",
    status: "Qualifizieren",
    score: 88,
    budget: "bis 520.000 Euro",
    intent: "Finanzierung vorgeprüft, 3 Zimmer in Graz",
    nextAction: "Termin vorschlagen",
    receivedAt: "2026-05-10T17:45:00+02:00",
    slaDueAt: "2026-05-11T16:00:00+02:00",
    lastContactAt: "2026-05-02T17:48:00+02:00",
    nextContactAt: "2026-05-11T16:00:00+02:00",
    region: "Steiermark",
    objectType: "Wohnung",
    rooms: 3,
    areaSqm: 78,
    buyerProfile: {
      budgetFrom: 420000,
      budgetTo: 540000,
      financingStatus: "vorqualifiziert",
      useCase: "Eigennutzung",
    },
    assignedToUserId: "user_sales_graz",
  },
  {
    id: "lead_daniel_hofer",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    contactId: "contact_daniel_hofer",
    source: "ImmobilienScout",
    type: "Investor",
    status: "Termin offen",
    score: 84,
    budget: "ab 450.000 Euro",
    intent: "Kapitalanlage mit Vermietungspotenzial",
    nextAction: "Exposé senden",
    receivedAt: "2026-05-11T08:10:00+02:00",
    slaDueAt: "2026-05-11T12:00:00+02:00",
    lastContactAt: "2026-04-21T08:13:00+02:00",
    nextContactAt: "2026-05-12T11:30:00+02:00",
    region: "Tirol",
    objectType: "Wohnung",
    areaSqm: 70,
    investorProfile: {
      investmentVolumeFrom: 450000,
      investmentVolumeTo: 900000,
      grossYieldExpectation: 4.2,
      netYieldExpectation: 3.1,
      investmentType: "Anlegerwohnung",
      financingStatus: "Eigenmittel",
      previousPurchases: 2,
    },
    assignedToUserId: "user_franz",
  },
  {
    id: "lead_elena_markovic",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_elena_markovic",
    source: "Empfehlung",
    type: "Käufer",
    status: "Termin offen",
    score: 93,
    budget: "480.000 bis 610.000 Euro",
    intent: "Reservierungsnah, sucht familienfreundliche Wohnung",
    nextAction: "Besichtigungsunterlagen vorbereiten",
    receivedAt: "2026-05-08T12:40:00+02:00",
    slaDueAt: "2026-05-11T15:45:00+02:00",
    lastContactAt: "2026-04-30T12:40:00+02:00",
    nextContactAt: "2026-05-11T15:45:00+02:00",
    region: "Steiermark",
    objectType: "Neubau",
    rooms: 4,
    areaSqm: 92,
    hotStatus: true,
    buyerProfile: {
      budgetFrom: 480000,
      budgetTo: 610000,
      financingStatus: "Finanzierungszusage",
      useCase: "Eigennutzung",
    },
    assignedToUserId: "user_sales_graz",
  },
  {
    id: "lead_lukas_falkner",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    contactId: "contact_lukas_falkner",
    source: "Website Funnel",
    type: "Investor",
    status: "Übergabe",
    score: 76,
    budget: "ab 1.200.000 Euro",
    intent: "Sucht Zinshaus mit stabiler Vermietung",
    nextAction: "Entscheider anrufen",
    receivedAt: "2026-05-05T11:10:00+02:00",
    slaDueAt: "2026-05-12T10:00:00+02:00",
    lastContactAt: "2026-05-10T11:15:00+02:00",
    nextContactAt: "2026-05-12T10:00:00+02:00",
    region: "Wien",
    objectType: "Zinshaus",
    areaSqm: 420,
    investorProfile: {
      investmentVolumeFrom: 1200000,
      investmentVolumeTo: 2600000,
      grossYieldExpectation: 3.8,
      netYieldExpectation: 2.8,
      investmentType: "Zinshaus",
      financingStatus: "vorqualifiziert",
      previousPurchases: 0,
    },
    assignedToUserId: "user_franz",
  },
];

export const sellerListings: SellerListing[] = [
  {
    id: "listing_anna_wilten",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    sellerLeadId: "lead_anna_berger",
    title: "3-Zimmer Wohnung Innsbruck-Wilten",
    address: "Innsbruck, Wilten",
    region: "Tirol",
    objectType: "Wohnung",
    areaSqm: 84,
    rooms: 3,
    yearBuilt: 1998,
    marketValue: 420000,
    targetPrice: 445000,
    expectedGrossYield: 3.6,
    mandateEndsAt: "2026-06-18",
    createdAt: "2026-05-11T09:25:00+02:00",
  },
  {
    id: "listing_graz_neubau_b12",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    sellerLeadId: "lead_anna_berger",
    title: "Neubau Einheit B12 Graz",
    address: "Graz, Jakomini",
    region: "Steiermark",
    objectType: "Neubau",
    areaSqm: 91,
    rooms: 4,
    yearBuilt: 2026,
    marketValue: 545000,
    targetPrice: 558000,
    expectedGrossYield: 3.3,
    mandateEndsAt: "2026-07-28",
    createdAt: "2026-05-09T10:00:00+02:00",
  },
];

export const deals: Deal[] = [
  {
    id: "deal_anna_berger",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    contactId: "contact_anna_berger",
    organizationId: "org_berger_family",
    ownerUserId: "user_franz",
    leadId: "lead_anna_berger",
    name: "Verkauf Eigentumswohnung Berger",
    stage: "Neuer Lead",
    value: "420.000",
    probability: 42,
    expectedCloseDate: "2026-08-15",
    riskLevel: "mittel",
    source: "WhatsApp",
    nextAction: "Rückruf heute",
  },
  {
    id: "deal_mira_klein",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_mira_klein",
    organizationId: "org_klein_household",
    ownerUserId: "user_sales_graz",
    leadId: "lead_mira_klein",
    name: "Wohnpark Graz Einheit B12",
    stage: "Qualifiziert",
    value: "510.000",
    probability: 64,
    expectedCloseDate: "2026-06-20",
    riskLevel: "niedrig",
    source: "Website Funnel",
    nextAction: "Termin vorschlagen",
  },
  {
    id: "deal_daniel_hofer",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    contactId: "contact_daniel_hofer",
    organizationId: "org_hofer_invest",
    ownerUserId: "user_franz",
    leadId: "lead_daniel_hofer",
    name: "Investmentobjekt Wien Hofer",
    stage: "Neuer Lead",
    value: "450.000",
    probability: 38,
    expectedCloseDate: "2026-07-31",
    riskLevel: "mittel",
    source: "Instagram",
    nextAction: "Exposé senden",
  },
  {
    id: "deal_thomas_reiter",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_thomas_reiter",
    organizationId: "org_reiter_development",
    ownerUserId: "user_franz",
    name: "Bauträger Kooperation Reiter",
    stage: "Termin gebucht",
    value: "620.000",
    probability: 58,
    expectedCloseDate: "2026-07-10",
    riskLevel: "niedrig",
    source: "Microsoft 365",
    nextAction: "Teams Link prüfen",
  },
  {
    id: "deal_elena_markovic",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_elena_markovic",
    organizationId: "org_markovic_household",
    ownerUserId: "user_sales_graz",
    name: "Wohnpark Graz Besichtigung Markovic",
    stage: "Besichtigung",
    value: "510.000",
    probability: 78,
    expectedCloseDate: "2026-06-05",
    riskLevel: "niedrig",
    source: "Website Funnel",
    nextAction: "Unterlagen vorbereiten",
  },
  {
    id: "deal_lukas_falkner",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    contactId: "contact_lukas_falkner",
    organizationId: "org_falkner_group",
    ownerUserId: "user_franz",
    name: "Projektvertrieb Falkner GmbH",
    stage: "Abschluss",
    value: "284.000",
    probability: 86,
    expectedCloseDate: "2026-05-28",
    riskLevel: "mittel",
    source: "Manual",
    nextAction: "Entscheider anrufen",
  },
];

export const pipeline: PipelineStage[] = [
  {
    title: "Neuer Lead",
    total: 18,
    value: "1,1 Mio.",
    cards: [
      {
        name: "Anna Berger",
        label: "Eigentümerin",
        detail: "Verkaufsabsicht in 3 Monaten",
        next: "Rückruf heute",
        score: 91,
      },
      {
        name: "Daniel Hofer",
        label: "Investor",
        detail: "Budget ab 450.000 Euro",
        next: "Exposé senden",
        score: 84,
      },
    ],
  },
  {
    title: "Qualifiziert",
    total: 11,
    value: "860.000",
    cards: [
      {
        name: "Mira Klein",
        label: "Käuferin",
        detail: "Finanzierung vorgeprüft",
        next: "Termin vorschlagen",
        score: 88,
      },
    ],
  },
  {
    title: "Termin gebucht",
    total: 7,
    value: "620.000",
    cards: [
      {
        name: "Thomas Reiter",
        label: "Bauträger",
        detail: "Projektgespräch morgen",
        next: "Teams Link prüfen",
        score: 79,
      },
    ],
  },
  {
    title: "Besichtigung",
    total: 5,
    value: "510.000",
    cards: [
      {
        name: "Elena Markovic",
        label: "Neubau Graz",
        detail: "Einheit B12 reservierbar",
        next: "Unterlagen vorbereiten",
        score: 93,
      },
    ],
  },
  {
    title: "Abschluss",
    total: 3,
    value: "284.000",
    cards: [
      {
        name: "Lukas Falkner",
        label: "Projektvertrieb",
        detail: "Angebot in Prüfung",
        next: "Entscheider anrufen",
        score: 76,
      },
    ],
  },
];

export const tasks: Task[] = [
  {
    id: "task_anna_callback",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    contactId: "contact_anna_berger",
    leadId: "lead_anna_berger",
    title: "Rückruf Verkäufer-Lead Anna Berger",
    project: "Seller Leads Linz",
    due: "Heute 14:30",
    priority: "Hoch",
    status: "open",
  },
  {
    id: "task_knowledge_graz",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    title: "Wissensdatenbank für Neubau Graz prüfen",
    project: "Wohnpark Graz",
    due: "Heute 16:00",
    priority: "Mittel",
    status: "open",
  },
  {
    id: "task_newsletter_segment",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    title: "Newsletter Opt-in Segment Käufer aktualisieren",
    project: "Novalure.eu",
    due: "Morgen",
    priority: "Mittel",
    status: "open",
  },
  {
    id: "task_calendar_connect",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    title: "Teams-Kalender Projekt Wohnpark verbinden",
    project: "Wohnpark Graz",
    due: "Diese Woche",
    priority: "Normal",
    status: "open",
  },
  {
    id: "task_elena_docs",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_elena_markovic",
    title: "Besichtigungsunterlagen für Elena Markovic vorbereiten",
    project: "Wohnpark Graz",
    due: "Heute 15:45",
    priority: "Hoch",
    status: "open",
  },
  {
    id: "task_falkner_decider",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    contactId: "contact_lukas_falkner",
    title: "Entscheider bei Falkner GmbH anrufen",
    project: "Novalure.eu",
    due: "Morgen",
    priority: "Mittel",
    status: "open",
  },
];

export const calendarEvents: CalendarEvent[] = [
  {
    id: "event_mira_viewing",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_mira_klein",
    leadId: "lead_mira_klein",
    title: "Besichtigung Einheit B12 mit Mira Klein",
    startsAt: "2026-05-11T16:30:00+02:00",
    endsAt: "2026-05-11T17:15:00+02:00",
    location: "Teams",
    status: "vorbereiten",
    preparation: [
      "Exposé und Grundriss Einheit B12 prüfen",
      "Finanzierungsstatus als Gesprächspunkt notieren",
      "Nächsten Schritt im Deal vorbereiten",
    ],
    outcomeGoal: "Besichtigung bestätigen und Reservierungsfenster klären.",
    ownerUserId: "user_sales_graz",
    teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/wohnpark-b12",
  },
  {
    id: "event_thomas_project",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_thomas_reiter",
    title: "Projektgespräch Reiter Development",
    startsAt: "2026-05-12T09:00:00+02:00",
    endsAt: "2026-05-12T10:00:00+02:00",
    location: "Teams",
    status: "bestätigt",
    preparation: [
      "Projektvertriebsmodell vorbereiten",
      "Offene Kalender- und Teams-Integration zeigen",
      "Entscheider und Rollen dokumentieren",
    ],
    outcomeGoal: "Kooperationsrahmen und nächsten Entscheidertermin sichern.",
    ownerUserId: "user_franz",
    teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/reiter-development",
  },
  {
    id: "event_anna_callback",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    contactId: "contact_anna_berger",
    leadId: "lead_anna_berger",
    title: "Rückruf Verkauf Eigentumswohnung Berger",
    startsAt: "2026-05-11T14:30:00+02:00",
    endsAt: "2026-05-11T14:45:00+02:00",
    location: "Telefon",
    status: "nachfassen",
    preparation: [
      "Bewertungsrahmen und Verkaufsablauf bereitlegen",
      "Consent für WhatsApp-Follow-up prüfen",
      "Nächste Bewertung als Aufgabe anlegen",
    ],
    outcomeGoal: "Verkaufsabsicht validieren und Bewertungsunterlagen anfordern.",
    ownerUserId: "user_franz",
  },
  {
    id: "event_daniel_invest",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    contactId: "contact_daniel_hofer",
    leadId: "lead_daniel_hofer",
    title: "Investment-Call Daniel Hofer",
    startsAt: "2026-05-12T11:30:00+02:00",
    endsAt: "2026-05-12T12:00:00+02:00",
    location: "Teams",
    status: "geplant",
    preparation: [
      "Renditeannahmen und Beispielobjekte sammeln",
      "Budget ab 450.000 Euro im Gespräch bestätigen",
      "Newsletter-Segment Investment vormerken",
    ],
    outcomeGoal: "Investmentprofil schärfen und passenden Deal qualifizieren.",
    ownerUserId: "user_franz",
    teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/daniel-hofer-invest",
  },
];

export const funnels: Funnel[] = [
  {
    id: "funnel_wohnpark_buyer",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Wohnpark Graz Käufer-Funnel",
    goal: "Qualifizierte Besichtigung für Neubau-Einheiten buchen",
    audience: "Käufer",
    entryChannel: "Website",
    status: "aktiv",
    visits: 1840,
    leads: 31,
    conversionRate: 1.7,
    ownerUserId: "user_sales_graz",
  },
  {
    id: "funnel_seller_linz_whatsapp",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    name: "Seller Leads Linz WhatsApp-Funnel",
    goal: "Eigentümer mit Verkaufsabsicht in Bewertungsgespräch bringen",
    audience: "Verkäufer",
    entryChannel: "WhatsApp",
    status: "optimieren",
    visits: 1260,
    leads: 44,
    conversionRate: 3.5,
    ownerUserId: "user_franz",
  },
  {
    id: "funnel_investment_wien_instagram",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Investment Wien Instagram-Funnel",
    goal: "Investorenprofil und Budget automatisch qualifizieren",
    audience: "Investor",
    entryChannel: "Instagram",
    status: "aktiv",
    visits: 980,
    leads: 18,
    conversionRate: 1.8,
    ownerUserId: "user_franz",
  },
  {
    id: "funnel_novalure_newsletter",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    name: "Novalure Newsletter Opt-in",
    goal: "Website-Besucher in Newsletter- und CRM-Segmente übernehmen",
    audience: "Käufer",
    entryChannel: "Newsletter",
    status: "entwurf",
    visits: 1420,
    leads: 22,
    conversionRate: 1.5,
    ownerUserId: "user_franz",
  },
];

export const funnelSteps: FunnelStep[] = [
  {
    id: "step_wohnpark_landing",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    funnelId: "funnel_wohnpark_buyer",
    name: "Projekt-Landingpage",
    channel: "Landingpage",
    status: "aktiv",
    visits: 1840,
    leads: 126,
    conversionRate: 6.8,
    dropOffReason: "Mobile Nutzer springen bei langer Einheitenliste ab.",
    nextOptimization: "Einheitenfilter und schnellere Anfrage-Schaltfläche testen.",
  },
  {
    id: "step_wohnpark_form",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    funnelId: "funnel_wohnpark_buyer",
    name: "Finanzierungs- und Besichtigungsformular",
    channel: "Website",
    status: "prüfen",
    visits: 126,
    leads: 31,
    conversionRate: 24.6,
    dropOffReason: "Budgetfrage wirkt für kalte Leads zu früh.",
    nextOptimization: "Budgetfrage optional machen und mit Bot nachqualifizieren.",
  },
  {
    id: "step_seller_ad",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    funnelId: "funnel_seller_linz_whatsapp",
    name: "Eigentümer-Anzeige",
    channel: "Landingpage",
    status: "aktiv",
    visits: 1260,
    leads: 104,
    conversionRate: 8.3,
    dropOffReason: "Viele Klicks ohne konkrete Verkaufsabsicht.",
    nextOptimization: "Anzeigentext stärker auf Bewertung und Verkaufszeitpunkt fokussieren.",
  },
  {
    id: "step_seller_whatsapp",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    funnelId: "funnel_seller_linz_whatsapp",
    name: "WhatsApp Bot Qualifizierung",
    channel: "WhatsApp",
    status: "prüfen",
    visits: 104,
    leads: 44,
    conversionRate: 42.3,
    dropOffReason: "Objektdaten werden noch nicht vollständig abgefragt.",
    nextOptimization: "Adresse, Objektart und Verkaufszeitraum als Pflichtsignale ergänzen.",
    botRuleId: "bot_rule_whatsapp_auto",
  },
  {
    id: "step_investment_instagram",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    funnelId: "funnel_investment_wien_instagram",
    name: "Instagram DM Einstieg",
    channel: "Instagram",
    status: "aktiv",
    visits: 980,
    leads: 64,
    conversionRate: 6.5,
    dropOffReason: "Renditeerwartung wird uneinheitlich beschrieben.",
    nextOptimization: "Antwortvorlagen nach Budget, Rendite und Haltedauer segmentieren.",
    botRuleId: "bot_rule_instagram_auto",
  },
  {
    id: "step_investment_booking",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    funnelId: "funnel_investment_wien_instagram",
    name: "Terminbuchung Investment-Call",
    channel: "Website",
    status: "blockiert",
    visits: 64,
    leads: 18,
    conversionRate: 28.1,
    dropOffReason: "Kalender-Slots sind noch nicht automatisch synchronisiert.",
    nextOptimization: "Microsoft 365 Kalenderverfügbarkeit direkt anbieten.",
  },
  {
    id: "step_novalure_newsletter",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    funnelId: "funnel_novalure_newsletter",
    name: "Newsletter Opt-in Modul",
    channel: "Newsletter",
    status: "entwurf",
    visits: 1420,
    leads: 22,
    conversionRate: 1.5,
    dropOffReason: "Mehrwert des Newsletters ist noch nicht konkret genug.",
    nextOptimization: "Segmentierte Inhalte für Käufer, Eigentümer und Investoren anbieten.",
  },
];

export const newsletterTemplates: NewsletterTemplate[] = [
  {
    id: "template_project_update",
    workspaceId: workspace.id,
    name: "Projektupdate mit Besichtigung",
    category: "Projektupdate",
    language: "de",
    status: "bereit",
    subjectPattern: "{{project_name}}: neue Einheit und Besichtigungsfenster",
    previewPattern: "Kurzupdate, Grundriss und nächster Termin für {{contact_first_name}}.",
    blocks: [
      "Persönliche Einleitung mit Projektbezug",
      "Projekt- oder Einheit-Update",
      "Kalender-CTA für Besichtigung",
      "Kontaktperson und Antwortmöglichkeit",
    ],
    personalizationFields: ["contact_first_name", "project_name", "unit_name", "calendar_link"],
  },
  {
    id: "template_seller_valuation",
    workspaceId: workspace.id,
    name: "Eigentümer-Bewertung",
    category: "Bewertung",
    language: "de",
    status: "bereit",
    subjectPattern: "Was ist Ihre Immobilie in {{city}} aktuell wert?",
    previewPattern: "Bewertung, Verkaufszeitpunkt und nächste Schritte kompakt erklärt.",
    blocks: [
      "Marktimpuls nach Stadt",
      "Bewertungs-Checkliste",
      "Antwort-CTA für Rückruf",
      "Consent- und Datenschutz-Hinweis",
    ],
    personalizationFields: ["contact_first_name", "city", "property_type", "callback_link"],
  },
  {
    id: "template_investment_briefing",
    workspaceId: workspace.id,
    name: "Investment-Briefing",
    category: "Investment",
    language: "de",
    status: "bereit",
    subjectPattern: "{{city}} Investment: Rendite, Lage und Vermietbarkeit",
    previewPattern: "Drei Punkte, die vor dem nächsten Investment-Call wichtig sind.",
    blocks: [
      "Renditeannahmen",
      "Budget- und Risikoprofil",
      "Teams-Termin CTA",
      "Nächster Deal-Schritt",
    ],
    personalizationFields: ["contact_first_name", "city", "budget", "teams_link"],
  },
  {
    id: "template_reactivation",
    workspaceId: workspace.id,
    name: "Reaktivierung warmer Kontakte",
    category: "Reaktivierung",
    language: "de",
    status: "entwurf",
    subjectPattern: "Sind Immobilienprojekte für Sie noch relevant?",
    previewPattern: "Ein kurzer Abgleich, damit Sie nur passende Updates erhalten.",
    blocks: [
      "Kurzer Relevanz-Check",
      "Interessenpräferenz",
      "Preference-Center Hinweis",
      "Abmelde- und Datenschutz-Hinweis",
    ],
    personalizationFields: ["contact_first_name", "preference_center_url"],
  },
];

export const newsletterSegments: NewsletterSegment[] = [
  {
    id: "segment_buyer_graz",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Käufer Graz mit Besichtigungsinteresse",
    audience: "Käufer",
    language: "de",
    source: "Funnel",
    contacts: 126,
    optIns: 84,
    health: "bereit",
    rules: [
      "Newsletter Opt-in vorhanden",
      "Interesse an Neubau oder 3-Zimmer-Wohnung",
      "Projekt Wohnpark Graz zugeordnet",
    ],
    resendAudienceId: "aud_buyer_graz",
  },
  {
    id: "segment_seller_linz",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    name: "Eigentümer Linz Verkaufsabsicht",
    audience: "Verkäufer",
    language: "de",
    source: "CRM",
    contacts: 104,
    optIns: 61,
    health: "prüfen",
    rules: [
      "WhatsApp oder Telefon Consent prüfen",
      "Verkaufszeitraum unter 12 Monate",
      "Objektdaten zumindest teilweise vorhanden",
    ],
    resendAudienceId: "aud_seller_linz",
  },
  {
    id: "segment_investors_wien",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Investoren Wien Renditeprofil",
    audience: "Investor",
    language: "de",
    source: "Funnel",
    contacts: 64,
    optIns: 39,
    health: "wachstum",
    rules: [
      "Budget ab 450.000 Euro",
      "Interesse an Vermietung oder Rendite",
      "Instagram oder Website Quelle",
    ],
    resendAudienceId: "aud_investors_wien",
  },
  {
    id: "segment_workspace_digest",
    workspaceId: workspace.id,
    name: "Workspace Newsletter Allgemein",
    audience: "Alle",
    language: "de",
    source: "Resend",
    contacts: 812,
    optIns: 812,
    health: "bereit",
    rules: [
      "Globaler Newsletter Opt-in",
      "Keine Projektbindung",
      "Sprache Deutsch als Standard",
    ],
    resendAudienceId: "aud_workspace_general",
  },
];

export const newsletterCampaigns: NewsletterCampaign[] = [
  {
    id: "campaign_wohnpark_b12",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    segmentId: "segment_buyer_graz",
    templateId: "template_project_update",
    name: "Wohnpark Graz Einheit B12 Update",
    fromName: "Novalure Immobilien",
    fromEmail: "newsletter@novalure.eu",
    replyTo: "graz@novalure.local",
    subject: "Neue Informationen zur Einheit B12 im Wohnpark Graz",
    previewText: "Grundriss, Besichtigung und Reservierungsfenster für interessierte Käufer.",
    status: "geplant",
    goal: "Besichtigungstermine für qualifizierte Käufer erhöhen.",
    recipients: 84,
    sendAt: "2026-05-13T09:30:00+02:00",
    contentBlocks: [
      "Projekt-Update und verfügbare Einheiten",
      "Besichtigungsfenster mit Microsoft 365 Kalenderlink",
      "Antwort-CTA für Rückfragen an Sales Graz",
    ],
    ownerUserId: "user_sales_graz",
    utmCampaign: "wohnpark_b12_update",
    abTest: {
      variantA: "Neue Informationen zur Einheit B12 im Wohnpark Graz",
      variantB: "Wohnpark Graz: Ist Einheit B12 passend für Sie?",
      testSizePercent: 20,
      winnerMetric: "click",
    },
  },
  {
    id: "campaign_seller_linz_value",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    segmentId: "segment_seller_linz",
    templateId: "template_seller_valuation",
    name: "Eigentümer Linz Bewertungsimpuls",
    fromName: "Franz von Novalure",
    fromEmail: "franz@novalure.eu",
    replyTo: "franz@novalure.local",
    subject: "Was ist Ihre Wohnung in Linz aktuell wert?",
    previewText: "Kurzbewertung, Verkaufszeitpunkt und nächste Schritte für Eigentümer.",
    status: "entwurf",
    goal: "Bewertungsgespräche aus warmen Eigentümer-Leads erzeugen.",
    recipients: 61,
    contentBlocks: [
      "Marktimpuls Linz kompakt",
      "Checkliste für Verkaufsabsicht",
      "WhatsApp Rückfrage mit Consent-Hinweis",
    ],
    ownerUserId: "user_franz",
    utmCampaign: "seller_linz_valuation",
  },
  {
    id: "campaign_investment_yield",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    segmentId: "segment_investors_wien",
    templateId: "template_investment_briefing",
    name: "Investment Wien Renditebriefing",
    fromName: "Novalure Investment",
    fromEmail: "investment@novalure.eu",
    replyTo: "franz@novalure.local",
    subject: "Investmentprofil Wien: Rendite, Lage und Vermietbarkeit",
    previewText: "Drei Punkte, die Investoren vor dem nächsten Call prüfen sollten.",
    status: "bereit",
    goal: "Investment-Calls vorbereiten und Budgetqualität erhöhen.",
    recipients: 39,
    sendAt: "2026-05-12T08:00:00+02:00",
    contentBlocks: [
      "Renditeannahmen erklären",
      "Budget und Haltedauer abfragen",
      "Teams-Termin für Investment-Call anbieten",
    ],
    ownerUserId: "user_franz",
    utmCampaign: "investment_wien_yield",
    abTest: {
      variantA: "Investmentprofil Wien: Rendite, Lage und Vermietbarkeit",
      variantB: "Wien-Investment: passt dieses Profil zu Ihrer Strategie?",
      testSizePercent: 30,
      winnerMetric: "open",
    },
  },
  {
    id: "campaign_workspace_monthly",
    workspaceId: workspace.id,
    segmentId: "segment_workspace_digest",
    templateId: "template_reactivation",
    name: "Novalure Monatsupdate",
    fromName: "Novalure",
    fromEmail: "newsletter@novalure.eu",
    replyTo: "hello@novalure.eu",
    subject: "Neue Projekte, Marktchancen und Immobilien-Updates",
    previewText: "Ein kompakter Überblick über aktuelle Chancen und nächste Termine.",
    status: "gesendet",
    goal: "Bestandskontakte reaktivieren und Projektinteresse messen.",
    recipients: 812,
    sendAt: "2026-05-01T10:00:00+02:00",
    openRate: 42.8,
    clickRate: 7.4,
    bounceRate: 0.4,
    unsubscribeRate: 0.2,
    contentBlocks: [
      "Projektüberblick",
      "Top-Immobilien und Marktimpuls",
      "CTA zur Projektberatung",
    ],
    ownerUserId: "user_franz",
    utmCampaign: "workspace_monthly_update",
  },
];

export const newsletterAutomations: NewsletterAutomation[] = [
  {
    id: "newsletter_auto_welcome_buyer",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Willkommensserie Käufer Graz",
    trigger: "Kontakt tritt Segment Käufer Graz bei",
    segmentId: "segment_buyer_graz",
    status: "aktiv",
    goal: "Neue Käufer innerhalb von 48 Stunden zum Besichtigungstermin führen.",
    steps: [
      { delay: "Sofort", channel: "Email", action: "Projektupdate und verfügbare Einheiten senden" },
      { delay: "1 Tag", channel: "Aufgabe", action: "Hot Lead prüfen und Rückruf vorbereiten" },
      { delay: "2 Tage", channel: "Email", action: "Besichtigungsfenster und Kalenderlink nachfassen" },
    ],
  },
  {
    id: "newsletter_auto_seller_reactivation",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    name: "Eigentümer Reaktivierung",
    trigger: "Kein Kontakt seit 14 Tagen und Verkaufszeitraum unter 12 Monate",
    segmentId: "segment_seller_linz",
    status: "entwurf",
    goal: "Warme Eigentümer in Bewertungsgespräche zurückholen.",
    steps: [
      { delay: "Sofort", channel: "Email", action: "Bewertungsimpuls senden" },
      { delay: "2 Tage", channel: "WhatsApp", action: "Kurze Rückfrage mit Consent prüfen" },
      { delay: "3 Tage", channel: "Aufgabe", action: "Persönlichen Rückruf einplanen" },
    ],
  },
  {
    id: "newsletter_auto_investor_briefing",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Investment Briefing vor Call",
    trigger: "Investment-Call im Kalender gebucht",
    segmentId: "segment_investors_wien",
    status: "aktiv",
    goal: "Investoren vor dem Termin qualifizieren und bessere Gespräche führen.",
    steps: [
      { delay: "24 Stunden vorher", channel: "Email", action: "Renditebriefing senden" },
      { delay: "2 Stunden vorher", channel: "Aufgabe", action: "Budget und Fragen im CRM prüfen" },
    ],
  },
];

export const newsletterDeliverability: NewsletterDeliverability[] = [
  {
    id: "deliverability_novalure_main",
    workspaceId: workspace.id,
    domain: "novalure.eu",
    fromEmail: "newsletter@novalure.eu",
    status: "bereit",
    spf: "ok",
    dkim: "ok",
    dmarc: "ok",
    bounceRate: 0.4,
    complaintRate: 0.03,
    reputationScore: 94,
  },
  {
    id: "deliverability_novalure_investment",
    workspaceId: workspace.id,
    domain: "novalure.eu",
    fromEmail: "investment@novalure.eu",
    status: "prüfen",
    spf: "ok",
    dkim: "ok",
    dmarc: "prüfen",
    bounceRate: 0.8,
    complaintRate: 0.05,
    reputationScore: 87,
  },
];

export const newsletterSuppressions: NewsletterSuppression[] = [
  {
    id: "suppression_old_bounce",
    workspaceId: workspace.id,
    email: "old.lead@example.test",
    reason: "bounce",
    source: "Resend",
    capturedAt: "2026-05-04T10:12:00+02:00",
  },
  {
    id: "suppression_unsubscribe",
    workspaceId: workspace.id,
    email: "abmeldung@example.test",
    reason: "unsubscribe",
    source: "Preference Center",
    capturedAt: "2026-05-08T18:30:00+02:00",
  },
];

export const consents: ConsentRecord[] = [
  {
    id: "consent_anna_whatsapp",
    workspaceId: workspace.id,
    contactId: "contact_anna_berger",
    projectId: "project_seller_linz",
    channel: "WhatsApp",
    status: "Opt-in",
    source: "WhatsApp Bot",
    capturedAt: "2026-05-11T09:20:00+02:00",
  },
  {
    id: "consent_mira_newsletter",
    workspaceId: workspace.id,
    contactId: "contact_mira_klein",
    projectId: "project_wohnpark_graz",
    channel: "Newsletter",
    status: "Opt-in",
    source: "Website Funnel",
    capturedAt: "2026-05-10T17:45:00+02:00",
  },
  {
    id: "consent_daniel_crm",
    workspaceId: workspace.id,
    contactId: "contact_daniel_hofer",
    projectId: "project_investment_wien",
    channel: "Instagram",
    status: "Nur CRM",
    source: "Instagram DM",
    capturedAt: "2026-05-11T08:10:00+02:00",
  },
];

export const conversations: Conversation[] = [
  {
    id: "conversation_anna_whatsapp",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    contactId: "contact_anna_berger",
    leadId: "lead_anna_berger",
    channel: "WhatsApp",
    direction: "inbound",
    summary: "Möchte Verkaufspreis und Ablauf für Eigentumswohnung in Linz einschätzen.",
    sentiment: "hot",
    lastMessageAt: "2026-05-11T09:22:00+02:00",
  },
  {
    id: "conversation_mira_website",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_mira_klein",
    leadId: "lead_mira_klein",
    channel: "Website Bot",
    direction: "inbound",
    summary: "Interessiert sich für Einheit B12, Finanzierung ist laut Formular vorgeprüft.",
    sentiment: "hot",
    lastMessageAt: "2026-05-10T17:48:00+02:00",
  },
  {
    id: "conversation_daniel_instagram",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    contactId: "contact_daniel_hofer",
    leadId: "lead_daniel_hofer",
    channel: "Instagram",
    direction: "inbound",
    summary: "Fragt nach Investmentobjekten ab 450.000 Euro und Renditeannahmen.",
    sentiment: "warm",
    lastMessageAt: "2026-05-11T08:13:00+02:00",
  },
];

export const contactTimeline: ContactTimelineItem[] = [
  {
    id: "timeline_anna_whatsapp",
    workspaceId: workspace.id,
    contactId: "contact_anna_berger",
    organizationId: "org_berger_family",
    projectId: "project_seller_linz",
    channel: "WhatsApp",
    title: "WhatsApp Anfrage eingegangen",
    detail: "Verkaufspreis und Ablauf für Eigentumswohnung in Linz einschätzen.",
    occurredAt: "2026-05-11T09:22:00+02:00",
    outcome: "offen",
  },
  {
    id: "timeline_anna_task",
    workspaceId: workspace.id,
    contactId: "contact_anna_berger",
    organizationId: "org_berger_family",
    projectId: "project_seller_linz",
    channel: "Aufgabe",
    title: "Rückruf fällig",
    detail: "Kontakt vor Ablauf des Speed-to-Lead Fensters anrufen.",
    occurredAt: "2026-05-11T14:30:00+02:00",
    outcome: "risiko",
  },
  {
    id: "timeline_mira_website",
    workspaceId: workspace.id,
    contactId: "contact_mira_klein",
    organizationId: "org_klein_household",
    projectId: "project_wohnpark_graz",
    channel: "Website Bot",
    title: "Website Bot Qualifizierung",
    detail: "Einheit B12, Finanzierung vorgeprüft, Besichtigung als nächster Schritt.",
    occurredAt: "2026-05-10T17:48:00+02:00",
    outcome: "info",
  },
  {
    id: "timeline_daniel_instagram",
    workspaceId: workspace.id,
    contactId: "contact_daniel_hofer",
    organizationId: "org_hofer_invest",
    projectId: "project_investment_wien",
    channel: "Instagram",
    title: "Instagram Investment-Anfrage",
    detail: "Fragt nach Renditeannahmen und Investmentobjekten ab 450.000 Euro.",
    occurredAt: "2026-05-11T08:13:00+02:00",
    outcome: "offen",
  },
  {
    id: "timeline_thomas_meeting",
    workspaceId: workspace.id,
    contactId: "contact_thomas_reiter",
    organizationId: "org_reiter_development",
    projectId: "project_wohnpark_graz",
    channel: "Microsoft 365",
    title: "Projektgespräch geplant",
    detail: "Teams-Link und Unterlagen für Bauträger-Termin prüfen.",
    occurredAt: "2026-05-12T09:00:00+02:00",
    outcome: "offen",
  },
];

export const automations: Automation[] = [
  {
    id: "automation_whatsapp_bot",
    workspaceId: workspace.id,
    name: "WhatsApp Bot",
    channel: "WhatsApp",
    status: "Bereit",
    detail: "Antwortet nur mit freigegebenem Projektwissen.",
  },
  {
    id: "automation_instagram_qualifier",
    workspaceId: workspace.id,
    name: "Instagram Qualifier",
    channel: "Instagram",
    status: "Training",
    detail: "Fragt Budget, Lage und Zeithorizont ab.",
  },
  {
    id: "automation_microsoft_calendar",
    workspaceId: workspace.id,
    name: "Microsoft Kalender",
    channel: "Microsoft 365",
    status: "Verbinden",
    detail: "Erstellt Termine und Teams-Meetings pro Projekt.",
  },
  {
    id: "automation_resend_newsletter",
    workspaceId: workspace.id,
    name: "Resend Newsletter",
    channel: "E-Mail",
    status: "Geplant",
    detail: "Segmentiert Opt-ins nach Projekt und Lead-Typ.",
  },
];

export const botLanguageRules: BotLanguageRule[] = [
  {
    id: "bot_language_whatsapp_seller_linz",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    channel: "WhatsApp",
    mode: "auto",
    fallbackLanguage: "de",
    detectionSignals: ["chat", "profile", "workspace"],
    confidence: 94,
    promptRule: "Sprache aus Kundennachricht erkennen und in derselben Sprache antworten.",
  },
  {
    id: "bot_language_instagram_investment_wien",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    channel: "Instagram",
    mode: "auto",
    fallbackLanguage: "de",
    detectionSignals: ["chat", "form", "workspace"],
    confidence: 88,
    promptRule: "Bei gemischter Sprache kurze Antwort in der zuletzt verwendeten Kundensprache.",
  },
  {
    id: "bot_language_website_graz",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    channel: "Website Bot",
    mode: "auto",
    fallbackLanguage: "de",
    detectionSignals: ["browser", "form", "chat"],
    confidence: 91,
    promptRule: "Browser-Sprache als ersten Hinweis nutzen, danach Kundentext priorisieren.",
  },
  {
    id: "bot_language_newsletter_global",
    workspaceId: workspace.id,
    channel: "Newsletter",
    mode: "fixed",
    fallbackLanguage: "de",
    fixedLanguage: "de",
    detectionSignals: ["workspace"],
    confidence: 100,
    promptRule: "Newsletter standardmäßig auf Deutsch senden, bis Segment-Sprache vorhanden ist.",
  },
];

export const knowledgeBase: KnowledgeItem[] = [
  {
    id: "knowledge_wohnpark_expose",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Wohnpark Graz Exposé",
    items: 18,
    coverage: "92%",
    status: "approved",
  },
  {
    id: "knowledge_pricing_units",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Preislisten und Einheiten",
    items: 7,
    coverage: "81%",
    status: "needs-review",
  },
  {
    id: "knowledge_financing",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    name: "Finanzierungsfragen",
    items: 12,
    coverage: "76%",
    status: "needs-review",
  },
];
