import type {
  Automation,
  BotCallInsight,
  BotLeadWorkflow,
  BotLanguageRule,
  CalendarEvent,
  ConsentRecord,
  Contact,
  ContactRelationship,
  ContactTimelineItem,
  Conversation,
  CrmBot,
  CrmBotConversation,
  CrmBotTool,
  Deal,
  Funnel,
  FunnelStep,
  KnowledgeItem,
  Lead,
  LeadSequenceDefinition,
  LeadSequenceEvent,
  SellerListing,
  NewsletterAutomation,
  NewsletterCampaign,
  NewsletterDeliverability,
  NewsletterSegment,
  NewsletterSuppression,
  NewsletterTemplate,
  Organization,
  PipelineStage,
  PropertyBuilding,
  PropertyReservation,
  PropertyUnit,
  CustomerWorkspaceAccess,
  Project,
  Task,
  Workspace,
  WorkspaceUser,
} from "@/lib/crm-types";
import { botSelfServeSetup } from "@/lib/bots/omnichannel";

function dateAtOffset(days: number, hour = 10, minute = 0) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(hour, minute, 0, 0);
  return date;
}

function isoAtOffset(days: number, hour = 10, minute = 0) {
  return dateAtOffset(days, hour, minute).toISOString();
}

function isoInHours(hoursFromNow: number) {
  return new Date(Date.now() + hoursFromNow * 60 * 60 * 1000).toISOString();
}

function dateOnlyAtOffset(days: number) {
  return dateAtOffset(days, 12, 0).toISOString().slice(0, 10);
}

function dueLabelInHours(hoursFromNow: number) {
  const now = new Date();
  const date = new Date(now.getTime() + hoursFromNow * 60 * 60 * 1000);
  const time = `${String(date.getHours()).padStart(2, "0")}:${String(date.getMinutes()).padStart(2, "0")}`;
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
  const target = new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime();
  const dayDelta = Math.round((target - today) / (24 * 60 * 60 * 1000));

  if (dayDelta === 0) return `Heute ${time}`;
  if (dayDelta === 1) return `Morgen ${time}`;
  return date.toISOString().slice(0, 10);
}

export const workspace: Workspace = {
  id: "ws_novalure",
  name: "Novalure",
  plan: "Growth Workspace",
  activeProjects: 4,
  activeUsers: 12,
  activeCalendarProvider: "none",
  customerType: "novalure_internal",
  operatingModel: "novalure_internal",
  teamStructure: "small_team",
};

export const users: WorkspaceUser[] = [
  {
    id: "user_franz",
    workspaceId: workspace.id,
    name: "Franz",
    email: "franz@novalure.local",
    productRole: "platform_admin",
    role: "owner",
    status: "active",
  },
  {
    id: "user_sales_graz",
    workspaceId: workspace.id,
    name: "Sales Graz",
    email: "graz@novalure.local",
    productRole: "novalure_operator",
    role: "agent",
    status: "active",
  },
];

export const navigation = [
  "Übersicht",
  "Lead Inbox",
  "Pipelines",
  "Kontakte",
  "Aufgaben",
  "Funnels",
  "Bots",
  "Wissen",
  "Newsletter",
  "Kalender",
];

export const projects: Project[] = [
  {
    id: "project_wohnpark_graz",
    workspaceId: workspace.id,
    name: "Wohnpark Graz",
    type: "Neubau Vertrieb",
    leads: 31,
    revenue: "1,82 Mio.",
    status: "Aktiv",
    defaultPipelineId: "pipeline_wohnpark_graz",
  },
  {
    id: "project_investment_wien",
    workspaceId: workspace.id,
    name: "Investment Wien",
    type: "Kapitalanlage",
    leads: 18,
    revenue: "940.000",
    status: "Skaliert",
    defaultPipelineId: "pipeline_investment_wien",
  },
  {
    id: "project_seller_linz",
    workspaceId: workspace.id,
    name: "Seller Leads Linz",
    type: "Eigentümer Funnel",
    leads: 44,
    revenue: "680.000",
    status: "Review",
    defaultPipelineId: "pipeline_seller_linz",
  },
  {
    id: "project_novalure_eu",
    workspaceId: workspace.id,
    name: "Novalure.eu",
    type: "Website Leads",
    leads: 22,
    revenue: "410.000",
    status: "Aktiv",
    defaultPipelineId: "pipeline_novalure_eu",
  },
];

export const organizations: Organization[] = [
  {
    id: "org_berger_family",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    name: "Familie Berger",
    type: "Privat",
    city: "Linz",
    ownerUserId: "user_franz",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Opportunity",
    lastActivityAt: "2026-05-11T09:22:00+02:00",
  },
  {
    id: "org_klein_household",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Haushalt Klein",
    type: "Privat",
    city: "Graz",
    ownerUserId: "user_sales_graz",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Lead",
    lastActivityAt: "2026-05-10T17:48:00+02:00",
  },
  {
    id: "org_hofer_invest",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Hofer Invest",
    type: "Investmentgesellschaft",
    city: "Wien",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Opportunity",
    lastActivityAt: "2026-05-11T08:13:00+02:00",
  },
  {
    id: "org_reiter_development",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Reiter Development",
    type: "Bauträger",
    domain: "reiter-development.example",
    city: "Graz",
    ownerUserId: "user_franz",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Partner",
    lastActivityAt: "2026-05-12T09:00:00+02:00",
  },
  {
    id: "org_markovic_household",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Haushalt Markovic",
    type: "Privat",
    city: "Graz",
    ownerUserId: "user_sales_graz",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Opportunity",
    lastActivityAt: "2026-05-11T12:40:00+02:00",
  },
  {
    id: "org_falkner_group",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    name: "Falkner GmbH",
    type: "Immobilienagentur",
    domain: "falkner.example",
    city: "Wien",
    ownerUserId: "user_franz",
    openDeals: 1,
    activeContacts: 1,
    lifecycleStage: "Partner",
    lastActivityAt: "2026-05-10T11:15:00+02:00",
  },
];

export const customerWorkspaceAccess: CustomerWorkspaceAccess[] = [
  {
    id: "customer_access_reiter",
    workspaceId: workspace.id,
    organizationId: "org_reiter_development",
    projectId: "project_wohnpark_graz",
    customerName: "Reiter Development",
    ownerUserId: "user_franz",
    status: "onboarding",
    plan: "Developer Growth",
    invitedUsers: 5,
    activeUsers: 3,
    activationScore: 68,
    health: "attention",
    lastCustomerActivityAt: "2026-05-12T09:00:00+02:00",
    nextOnboardingAction: "Einheitenimport und Kundenrechte im Termin finalisieren.",
    risks: ["Einheitenbestand noch nicht vollständig", "Instagram Kanal noch nicht verbunden"],
  },
  {
    id: "customer_access_falkner",
    workspaceId: workspace.id,
    organizationId: "org_falkner_group",
    projectId: "project_novalure_eu",
    customerName: "Falkner GmbH",
    ownerUserId: "user_franz",
    status: "trial",
    plan: "Pilot Workspace",
    invitedUsers: 3,
    activeUsers: 1,
    activationScore: 54,
    health: "risk",
    lastCustomerActivityAt: "2026-05-10T11:15:00+02:00",
    nextOnboardingAction: "Entscheider-Call sichern und ersten Funnel live schalten.",
    risks: ["Nur ein aktiver Nutzer", "Noch keine finale Projektentscheidung"],
  },
];

export type Metric = {
  label: string;
  value: string;
  detail: string;
  tone: "emerald" | "blue" | "violet" | "amber";
};

export const metrics: Metric[] = [
  { label: "Neue Leads", value: "44", detail: "+12 diese Woche", tone: "emerald" },
  { label: "Gebuchte Termine", value: "9", detail: "Microsoft 365", tone: "blue" },
  { label: "Bot Gespräche", value: "126", detail: "WhatsApp und Instagram", tone: "violet" },
  { label: "Newsletter Opt-ins", value: "812", detail: "Resend Segmente", tone: "amber" },
];

export const contacts: Contact[] = [
  {
    id: "contact_anna_berger",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    organizationId: "org_berger_family",
    name: "Anna Berger",
    role: "Verkäufer",
    project: "Seller Leads Linz",
    source: "WhatsApp",
    intent: "Verkauf",
    consent: "Opt-in vorhanden",
    phone: "+43 660 000000",
  },
  {
    id: "contact_mira_klein",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    organizationId: "org_klein_household",
    name: "Mira Klein",
    role: "Käufer",
    project: "Wohnpark Graz",
    source: "Website Funnel",
    intent: "Besichtigung",
    consent: "Newsletter ja",
    email: "mira.klein@demo.novalure-crm.app",
  },
  {
    id: "contact_daniel_hofer",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    organizationId: "org_hofer_invest",
    name: "Daniel Hofer",
    role: "Investor",
    project: "Investment Wien",
    source: "Instagram",
    intent: "Kapitalanlage",
    consent: "Nur CRM",
  },
  {
    id: "contact_thomas_reiter",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    organizationId: "org_reiter_development",
    name: "Thomas Reiter",
    role: "Bauträger",
    project: "Wohnpark Graz",
    source: "Empfehlung",
    intent: "Projektgespräch",
    consent: "Nur CRM",
  },
  {
    id: "contact_elena_markovic",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    organizationId: "org_markovic_household",
    name: "Elena Markovic",
    role: "Käufer",
    project: "Wohnpark Graz",
    source: "Website Funnel",
    intent: "Besichtigung",
    consent: "Newsletter ja",
    email: "elena.markovic@demo.novalure-crm.app",
  },
  {
    id: "contact_lukas_falkner",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    organizationId: "org_falkner_group",
    name: "Lukas Falkner",
    role: "Makler",
    project: "Novalure.eu",
    source: "Manual",
    intent: "Projektvertrieb",
    consent: "Nur CRM",
    email: "lukas@falkner.example",
  },
];

export const contactRelationships: ContactRelationship[] = [
  {
    id: "rel_anna_owner",
    workspaceId: workspace.id,
    contactId: "contact_anna_berger",
    organizationId: "org_berger_family",
    projectId: "project_seller_linz",
    role: "Eigentümer",
    influence: "hoch",
    isPrimary: true,
  },
  {
    id: "rel_mira_buyer",
    workspaceId: workspace.id,
    contactId: "contact_mira_klein",
    organizationId: "org_klein_household",
    projectId: "project_wohnpark_graz",
    role: "Käufer",
    influence: "hoch",
    isPrimary: true,
  },
  {
    id: "rel_daniel_investor",
    workspaceId: workspace.id,
    contactId: "contact_daniel_hofer",
    organizationId: "org_hofer_invest",
    projectId: "project_investment_wien",
    role: "Investor",
    influence: "hoch",
    isPrimary: true,
  },
  {
    id: "rel_thomas_developer",
    workspaceId: workspace.id,
    contactId: "contact_thomas_reiter",
    organizationId: "org_reiter_development",
    projectId: "project_wohnpark_graz",
    role: "Bauträger",
    influence: "mittel",
    isPrimary: true,
  },
];

export const leads: Lead[] = [
  {
    id: "lead_anna_berger",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    contactId: "contact_anna_berger",
    source: "willhaben",
    type: "Verkäufer",
    status: "Neu",
    score: 91,
    intent: "Verkaufsabsicht in 3 Monaten",
    nextAction: "Rückruf heute",
    receivedAt: isoInHours(-2),
    slaDueAt: isoInHours(3),
    lastContactAt: isoInHours(-1),
    nextContactAt: isoInHours(3),
    region: "Tirol",
    objectType: "Wohnung",
    rooms: 3,
    areaSqm: 84,
    hotStatus: true,
    sellerProfile: {
      address: "Innsbruck, Wilten",
      yearBuilt: 1998,
      marketValue: 420000,
      askingPrice: 445000,
      sellingReason: "Familienumzug",
      competingBroker: false,
      brokerContractStatus: "in Verhandlung",
      commissionRate: 3,
    },
    assignedToUserId: "user_franz",
  },
  {
    id: "lead_mira_klein",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_mira_klein",
    source: "Website",
    type: "Käufer",
    status: "Qualifizieren",
    score: 88,
    budget: "bis 520.000 Euro",
    intent: "Finanzierung vorgeprüft, 3 Zimmer in Graz",
    nextAction: "Termin vorschlagen",
    receivedAt: isoInHours(-18),
    slaDueAt: isoInHours(6),
    lastContactAt: isoInHours(-12),
    nextContactAt: isoInHours(6),
    region: "Steiermark",
    objectType: "Wohnung",
    rooms: 3,
    areaSqm: 78,
    buyerProfile: {
      budgetFrom: 420000,
      budgetTo: 540000,
      financingStatus: "vorqualifiziert",
      useCase: "Eigennutzung",
    },
    assignedToUserId: "user_sales_graz",
  },
  {
    id: "lead_daniel_hofer",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    contactId: "contact_daniel_hofer",
    source: "ImmobilienScout",
    type: "Investor",
    status: "Termin offen",
    score: 84,
    budget: "ab 450.000 Euro",
    intent: "Kapitalanlage mit Vermietungspotenzial",
    nextAction: "Exposé senden",
    receivedAt: isoInHours(-4),
    slaDueAt: isoInHours(2),
    lastContactAt: isoInHours(-3),
    nextContactAt: isoInHours(24),
    region: "Tirol",
    objectType: "Wohnung",
    areaSqm: 70,
    investorProfile: {
      investmentVolumeFrom: 450000,
      investmentVolumeTo: 900000,
      grossYieldExpectation: 4.2,
      netYieldExpectation: 3.1,
      investmentType: "Anlegerwohnung",
      financingStatus: "Eigenmittel",
      previousPurchases: 2,
    },
    assignedToUserId: "user_franz",
  },
  {
    id: "lead_elena_markovic",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_elena_markovic",
    source: "Empfehlung",
    type: "Käufer",
    status: "Termin offen",
    score: 93,
    budget: "480.000 bis 610.000 Euro",
    intent: "Reservierungsnah, sucht familienfreundliche Wohnung",
    nextAction: "Besichtigungsunterlagen vorbereiten",
    receivedAt: isoInHours(-48),
    slaDueAt: isoInHours(28),
    lastContactAt: isoInHours(-20),
    nextContactAt: isoInHours(28),
    region: "Steiermark",
    objectType: "Neubau",
    rooms: 4,
    areaSqm: 92,
    hotStatus: true,
    buyerProfile: {
      budgetFrom: 480000,
      budgetTo: 610000,
      financingStatus: "Finanzierungszusage",
      useCase: "Eigennutzung",
    },
    assignedToUserId: "user_sales_graz",
  },
  {
    id: "lead_lukas_falkner",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    contactId: "contact_lukas_falkner",
    source: "Website Funnel",
    type: "Investor",
    status: "Übergabe",
    score: 76,
    budget: "ab 1.200.000 Euro",
    intent: "Sucht Zinshaus mit stabiler Vermietung",
    nextAction: "Entscheider anrufen",
    receivedAt: isoInHours(-72),
    slaDueAt: isoInHours(48),
    lastContactAt: isoInHours(-24),
    nextContactAt: isoInHours(48),
    region: "Wien",
    objectType: "Zinshaus",
    areaSqm: 420,
    investorProfile: {
      investmentVolumeFrom: 1200000,
      investmentVolumeTo: 2600000,
      grossYieldExpectation: 3.8,
      netYieldExpectation: 2.8,
      investmentType: "Zinshaus",
      financingStatus: "vorqualifiziert",
      previousPurchases: 0,
    },
    assignedToUserId: "user_franz",
  },
];

export const sellerListings: SellerListing[] = [
  {
    id: "listing_anna_wilten",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    sellerLeadId: "lead_anna_berger",
    title: "3-Zimmer Wohnung Innsbruck-Wilten",
    address: "Innsbruck, Wilten",
    region: "Tirol",
    objectType: "Wohnung",
    areaSqm: 84,
    rooms: 3,
    yearBuilt: 1998,
    marketValue: 420000,
    targetPrice: 445000,
    expectedGrossYield: 3.6,
    mandateEndsAt: "2026-06-18",
    createdAt: "2026-05-11T09:25:00+02:00",
  },
  {
    id: "listing_graz_neubau_b12",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    sellerLeadId: "lead_anna_berger",
    title: "Neubau Einheit B12 Graz",
    address: "Graz, Jakomini",
    region: "Steiermark",
    objectType: "Neubau",
    areaSqm: 91,
    rooms: 4,
    yearBuilt: 2026,
    marketValue: 545000,
    targetPrice: 558000,
    expectedGrossYield: 3.3,
    mandateEndsAt: "2026-07-28",
    createdAt: "2026-05-09T10:00:00+02:00",
  },
];

export const propertyBuildings: PropertyBuilding[] = [
  {
    id: "building_wohnpark_graz_b",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Wohnpark Graz Haus B",
    address: "Graz, Jakomini",
    completionDate: "2026-11-30",
    floors: 6,
  },
  {
    id: "building_investment_wien_a",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Investment Wien Haus A",
    address: "Wien, Favoriten",
    completionDate: "2026-09-15",
    floors: 8,
  },
];

export const propertyUnits: PropertyUnit[] = [
  {
    id: "unit_wohnpark_b12",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    buildingId: "building_wohnpark_graz_b",
    unitNumber: "B12",
    floor: 3,
    rooms: 3,
    areaSqm: 78,
    priceCents: 51000000,
    status: "reserved",
    buyerContactId: "contact_mira_klein",
    dealId: "deal_mira_klein",
    reservationId: "reservation_b12_mira",
    updatedAt: "2026-05-12T11:15:00+02:00",
  },
  {
    id: "unit_wohnpark_b14",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    buildingId: "building_wohnpark_graz_b",
    unitNumber: "B14",
    floor: 4,
    rooms: 4,
    areaSqm: 92,
    priceCents: 59800000,
    status: "available",
    buyerContactId: "contact_elena_markovic",
    dealId: "deal_elena_markovic",
    updatedAt: "2026-05-12T10:30:00+02:00",
  },
  {
    id: "unit_wohnpark_b18",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    buildingId: "building_wohnpark_graz_b",
    unitNumber: "B18",
    floor: 5,
    rooms: 2,
    areaSqm: 56,
    priceCents: 36500000,
    status: "blocked",
    updatedAt: "2026-05-10T08:00:00+02:00",
  },
  {
    id: "unit_investment_a07",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    buildingId: "building_investment_wien_a",
    unitNumber: "A07",
    floor: 2,
    rooms: 2,
    areaSqm: 64,
    priceCents: 45200000,
    status: "available",
    buyerContactId: "contact_daniel_hofer",
    dealId: "deal_daniel_hofer",
    updatedAt: "2026-05-12T09:40:00+02:00",
  },
  {
    id: "unit_investment_a15",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    buildingId: "building_investment_wien_a",
    unitNumber: "A15",
    floor: 5,
    rooms: 3,
    areaSqm: 82,
    priceCents: 62400000,
    status: "sold",
    updatedAt: "2026-05-08T13:20:00+02:00",
  },
];

export const propertyReservations: PropertyReservation[] = [
  {
    id: "reservation_b12_mira",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    unitId: "unit_wohnpark_b12",
    contactId: "contact_mira_klein",
    dealId: "deal_mira_klein",
    status: "reserved",
    expiresAt: isoAtOffset(3, 18, 0),
    depositCents: 1000000,
    contractMilestone: "offer_sent",
    nextAction: "Finanzierungsnachweis und Optionsfrist bestätigen.",
  },
  {
    id: "reservation_b14_elena_hold",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    unitId: "unit_wohnpark_b14",
    contactId: "contact_elena_markovic",
    dealId: "deal_elena_markovic",
    status: "hold",
    expiresAt: isoAtOffset(5, 12, 0),
    depositCents: 0,
    contractMilestone: "not_started",
    nextAction: "Besichtigung abschließen und Reservierungsentscheidung einholen.",
  },
];

export const deals: Deal[] = [
  {
    id: "deal_anna_berger",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    contactId: "contact_anna_berger",
    organizationId: "org_berger_family",
    ownerUserId: "user_franz",
    leadId: "lead_anna_berger",
    name: "Verkauf Eigentumswohnung Berger",
    stage: "Neu",
    value: "420.000",
    probability: 42,
    expectedCloseDate: dateOnlyAtOffset(75),
    riskLevel: "mittel",
    source: "WhatsApp",
    nextAction: "Rückruf heute",
  },
  {
    id: "deal_mira_klein",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_mira_klein",
    organizationId: "org_klein_household",
    ownerUserId: "user_sales_graz",
    leadId: "lead_mira_klein",
    name: "Wohnpark Graz Einheit B12",
    stage: "Termin vereinbaren",
    value: "510.000",
    probability: 64,
    expectedCloseDate: dateOnlyAtOffset(45),
    riskLevel: "niedrig",
    source: "Website Funnel",
    nextAction: "Termin vorschlagen",
  },
  {
    id: "deal_daniel_hofer",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    contactId: "contact_daniel_hofer",
    organizationId: "org_hofer_invest",
    ownerUserId: "user_franz",
    leadId: "lead_daniel_hofer",
    name: "Investmentobjekt Wien Hofer",
    stage: "Neu",
    value: "450.000",
    probability: 38,
    expectedCloseDate: dateOnlyAtOffset(60),
    riskLevel: "mittel",
    source: "Instagram",
    nextAction: "Exposé senden",
  },
  {
    id: "deal_thomas_reiter",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_thomas_reiter",
    organizationId: "org_reiter_development",
    ownerUserId: "user_franz",
    name: "Bauträger Kooperation Reiter",
    stage: "Termin gebucht",
    value: "620.000",
    probability: 58,
    expectedCloseDate: dateOnlyAtOffset(40),
    riskLevel: "niedrig",
    source: "Empfehlung",
    nextAction: "Teams Link prüfen",
  },
  {
    id: "deal_elena_markovic",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_elena_markovic",
    organizationId: "org_markovic_household",
    ownerUserId: "user_sales_graz",
    name: "Wohnpark Graz Besichtigung Markovic",
    stage: "Besichtigung/Beratung",
    value: "510.000",
    probability: 78,
    expectedCloseDate: dateOnlyAtOffset(28),
    riskLevel: "niedrig",
    source: "Website Funnel",
    nextAction: "Unterlagen vorbereiten",
  },
  {
    id: "deal_lukas_falkner",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    contactId: "contact_lukas_falkner",
    organizationId: "org_falkner_group",
    ownerUserId: "user_franz",
    name: "Projektvertrieb Falkner GmbH",
    stage: "Gewonnen",
    value: "284.000",
    probability: 86,
    expectedCloseDate: dateOnlyAtOffset(14),
    riskLevel: "mittel",
    source: "Manual",
    nextAction: "Entscheider anrufen",
  },
];

export const pipeline: PipelineStage[] = [
  {
    title: "Neu",
    total: 18,
    value: "1,1 Mio.",
    cards: [
      {
        name: "Anna Berger",
        label: "Eigentümerin",
        detail: "Verkaufsabsicht in 3 Monaten",
        next: "Rückruf heute",
        score: 91,
      },
      {
        name: "Daniel Hofer",
        label: "Investor",
        detail: "Budget ab 450.000 Euro",
        next: "Exposé senden",
        score: 84,
      },
    ],
  },
  {
    title: "Qualifizieren",
    total: 0,
    value: "0",
    cards: [],
  },
  {
    title: "Termin vereinbaren",
    total: 9,
    value: "510.000",
    cards: [
      {
        name: "Mira Klein",
        label: "Käuferin",
        detail: "Finanzierung vorgeprüft",
        next: "Termin vorschlagen",
        score: 88,
      },
    ],
  },
  {
    title: "Termin gebucht",
    total: 7,
    value: "620.000",
    cards: [
      {
        name: "Thomas Reiter",
        label: "Bauträger",
        detail: "Projektgespräch morgen",
        next: "Teams Link prüfen",
        score: 79,
      },
    ],
  },
  {
    title: "Besichtigung/Beratung",
    total: 5,
    value: "510.000",
    cards: [
      {
        name: "Elena Markovic",
        label: "Neubau Graz",
        detail: "Einheit B12 reservierbar",
        next: "Unterlagen vorbereiten",
        score: 93,
      },
    ],
  },
  {
    title: "Angebot/Reservierung",
    total: 2,
    value: "510.000",
    cards: [],
  },
  {
    title: "Abschlussprüfung",
    total: 1,
    value: "284.000",
    cards: [],
  },
  {
    title: "Gewonnen",
    total: 3,
    value: "284.000",
    cards: [
      {
        name: "Lukas Falkner",
        label: "Projektvertrieb",
        detail: "Angebot in Prüfung",
        next: "Entscheider anrufen",
        score: 76,
      },
    ],
  },
  {
    title: "Verloren",
    total: 0,
    value: "0",
    cards: [],
  },
  {
    title: "Disqualifiziert",
    total: 0,
    value: "0",
    cards: [],
  },
];

export const tasks: Task[] = [
  {
    id: "task_anna_callback",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    contactId: "contact_anna_berger",
    leadId: "lead_anna_berger",
    title: "Rückruf Verkäufer-Lead Anna Berger",
    project: "Seller Leads Linz",
    due: dueLabelInHours(2),
    priority: "Hoch",
    status: "open",
  },
  {
    id: "task_knowledge_graz",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    title: "Wissensdatenbank für Neubau Graz prüfen",
    project: "Wohnpark Graz",
    due: dueLabelInHours(5),
    priority: "Mittel",
    status: "open",
  },
  {
    id: "task_newsletter_segment",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    title: "Newsletter Opt-in Segment Käufer aktualisieren",
    project: "Novalure.eu",
    due: dueLabelInHours(24),
    priority: "Mittel",
    status: "open",
  },
  {
    id: "task_calendar_connect",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    title: "Teams-Kalender Projekt Wohnpark verbinden",
    project: "Wohnpark Graz",
    due: dueLabelInHours(72),
    priority: "Normal",
    status: "open",
  },
  {
    id: "task_elena_docs",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_elena_markovic",
    title: "Besichtigungsunterlagen für Elena Markovic vorbereiten",
    project: "Wohnpark Graz",
    due: dueLabelInHours(3),
    priority: "Hoch",
    status: "open",
  },
  {
    id: "task_falkner_decider",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    contactId: "contact_lukas_falkner",
    title: "Entscheider bei Falkner GmbH anrufen",
    project: "Novalure.eu",
    due: dueLabelInHours(26),
    priority: "Mittel",
    status: "open",
  },
];

export const calendarEvents: CalendarEvent[] = [
  {
    id: "event_mira_viewing",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_mira_klein",
    leadId: "lead_mira_klein",
    title: "Besichtigung Einheit B12 mit Mira Klein",
    startsAt: isoAtOffset(1, 16, 30),
    endsAt: isoAtOffset(1, 17, 15),
    location: "Teams",
    calendarProvider: "microsoft",
    meetingProvider: "microsoft-teams",
    status: "vorbereiten",
    preparation: [
      "Exposé und Grundriss Einheit B12 prüfen",
      "Finanzierungsstatus als Gesprächspunkt notieren",
      "Nächsten Schritt im Deal vorbereiten",
    ],
    outcomeGoal: "Besichtigung bestätigen und Reservierungsfenster klären.",
    ownerUserId: "user_sales_graz",
    teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/wohnpark-b12",
  },
  {
    id: "event_thomas_project",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_thomas_reiter",
    title: "Projektgespräch Reiter Development",
    startsAt: isoAtOffset(2, 9, 0),
    endsAt: isoAtOffset(2, 10, 0),
    location: "Teams",
    calendarProvider: "microsoft",
    meetingProvider: "microsoft-teams",
    status: "bestätigt",
    preparation: [
      "Projektvertriebsmodell vorbereiten",
      "Offene Kalender- und Teams-Integration zeigen",
      "Entscheider und Rollen dokumentieren",
    ],
    outcomeGoal: "Kooperationsrahmen und nächsten Entscheidertermin sichern.",
    ownerUserId: "user_franz",
    teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/reiter-development",
  },
  {
    id: "event_anna_callback",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    contactId: "contact_anna_berger",
    leadId: "lead_anna_berger",
    title: "Rückruf Verkauf Eigentumswohnung Berger",
    startsAt: isoInHours(4),
    endsAt: isoInHours(4.25),
    location: "Telefon",
    calendarProvider: "manual",
    meetingProvider: "phone",
    status: "nachfassen",
    preparation: [
      "Bewertungsrahmen und Verkaufsablauf bereitlegen",
      "Consent für WhatsApp-Follow-up prüfen",
      "Nächste Bewertung als Aufgabe anlegen",
    ],
    outcomeGoal: "Verkaufsabsicht validieren und Bewertungsunterlagen anfordern.",
    ownerUserId: "user_franz",
  },
  {
    id: "event_daniel_invest",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    contactId: "contact_daniel_hofer",
    leadId: "lead_daniel_hofer",
    title: "Investment-Call Daniel Hofer",
    startsAt: isoAtOffset(3, 11, 30),
    endsAt: isoAtOffset(3, 12, 0),
    location: "Google Meet",
    calendarProvider: "google",
    meetingProvider: "google-meet",
    status: "geplant",
    preparation: [
      "Renditeannahmen und Beispielobjekte sammeln",
      "Budget ab 450.000 Euro im Gespräch bestätigen",
      "Newsletter-Segment Investment vormerken",
    ],
    outcomeGoal: "Investmentprofil schärfen und passenden Deal qualifizieren.",
    ownerUserId: "user_franz",
    googleMeetJoinUrl: "https://meet.google.com/novalure-daniel-hofer",
  },
];

export const funnels: Funnel[] = [
  {
    id: "funnel_wohnpark_buyer",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Wohnpark Graz Käufer-Funnel",
    goal: "Qualifizierte Besichtigung für Neubau-Einheiten buchen",
    audience: "Käufer",
    entryChannel: "Website",
    status: "aktiv",
    visits: 1840,
    leads: 31,
    conversionRate: 1.7,
    ownerUserId: "user_sales_graz",
  },
  {
    id: "funnel_seller_linz_whatsapp",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    name: "Seller Leads Linz WhatsApp-Funnel",
    goal: "Eigentümer mit Verkaufsabsicht in Bewertungsgespräch bringen",
    audience: "Verkäufer",
    entryChannel: "WhatsApp",
    status: "optimieren",
    visits: 1260,
    leads: 44,
    conversionRate: 3.5,
    ownerUserId: "user_franz",
  },
  {
    id: "funnel_investment_wien_instagram",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Investment Wien Instagram-Funnel",
    goal: "Investorenprofil und Budget automatisch qualifizieren",
    audience: "Investor",
    entryChannel: "Instagram",
    status: "aktiv",
    visits: 980,
    leads: 18,
    conversionRate: 1.8,
    ownerUserId: "user_franz",
  },
  {
    id: "funnel_novalure_newsletter",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    name: "Novalure Newsletter Opt-in",
    goal: "Website-Besucher in Newsletter- und CRM-Segmente übernehmen",
    audience: "Käufer",
    entryChannel: "Newsletter",
    status: "entwurf",
    visits: 1420,
    leads: 22,
    conversionRate: 1.5,
    ownerUserId: "user_franz",
  },
];

export const funnelSteps: FunnelStep[] = [
  {
    id: "step_wohnpark_landing",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    funnelId: "funnel_wohnpark_buyer",
    name: "Projekt-Landingpage",
    channel: "Landingpage",
    status: "aktiv",
    visits: 1840,
    leads: 126,
    conversionRate: 6.8,
    dropOffReason: "Mobile Nutzer springen bei langer Einheitenliste ab.",
    nextOptimization: "Einheitenfilter und schnellere Anfrage-Schaltfläche testen.",
  },
  {
    id: "step_wohnpark_form",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    funnelId: "funnel_wohnpark_buyer",
    name: "Finanzierungs- und Besichtigungsformular",
    channel: "Website",
    status: "prüfen",
    visits: 126,
    leads: 31,
    conversionRate: 24.6,
    dropOffReason: "Budgetfrage wirkt für kalte Leads zu früh.",
    nextOptimization: "Budgetfrage optional machen und mit Bot nachqualifizieren.",
  },
  {
    id: "step_seller_ad",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    funnelId: "funnel_seller_linz_whatsapp",
    name: "Eigentümer-Anzeige",
    channel: "Landingpage",
    status: "aktiv",
    visits: 1260,
    leads: 104,
    conversionRate: 8.3,
    dropOffReason: "Viele Klicks ohne konkrete Verkaufsabsicht.",
    nextOptimization: "Anzeigentext stärker auf Bewertung und Verkaufszeitpunkt fokussieren.",
  },
  {
    id: "step_seller_whatsapp",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    funnelId: "funnel_seller_linz_whatsapp",
    name: "WhatsApp Bot Qualifizierung",
    channel: "WhatsApp",
    status: "prüfen",
    visits: 104,
    leads: 44,
    conversionRate: 42.3,
    dropOffReason: "Objektdaten werden noch nicht vollständig abgefragt.",
    nextOptimization: "Adresse, Objektart und Verkaufszeitraum als Pflichtsignale ergänzen.",
    botRuleId: "bot_rule_whatsapp_auto",
  },
  {
    id: "step_investment_instagram",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    funnelId: "funnel_investment_wien_instagram",
    name: "Instagram DM Einstieg",
    channel: "Instagram",
    status: "aktiv",
    visits: 980,
    leads: 64,
    conversionRate: 6.5,
    dropOffReason: "Renditeerwartung wird uneinheitlich beschrieben.",
    nextOptimization: "Antwortvorlagen nach Budget, Rendite und Haltedauer segmentieren.",
    botRuleId: "bot_rule_instagram_auto",
  },
  {
    id: "step_investment_booking",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    funnelId: "funnel_investment_wien_instagram",
    name: "Terminbuchung Investment-Call",
    channel: "Website",
    status: "blockiert",
    visits: 64,
    leads: 18,
    conversionRate: 28.1,
    dropOffReason: "Kalender-Slots sind noch nicht automatisch synchronisiert.",
    nextOptimization: "Microsoft 365 Kalenderverfügbarkeit direkt anbieten.",
  },
  {
    id: "step_novalure_newsletter",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    funnelId: "funnel_novalure_newsletter",
    name: "Newsletter Opt-in Modul",
    channel: "Newsletter",
    status: "entwurf",
    visits: 1420,
    leads: 22,
    conversionRate: 1.5,
    dropOffReason: "Mehrwert des Newsletters ist noch nicht konkret genug.",
    nextOptimization: "Segmentierte Inhalte für Käufer, Eigentümer und Investoren anbieten.",
  },
];

export const newsletterTemplates: NewsletterTemplate[] = [
  {
    id: "template_project_update",
    workspaceId: workspace.id,
    name: "Projektupdate mit Besichtigung",
    category: "Projektupdate",
    language: "de",
    status: "bereit",
    subjectPattern: "{{project_name}}: neue Einheit und Besichtigungsfenster",
    previewPattern: "Kurzupdate, Grundriss und nächster Termin für {{contact_first_name}}.",
    blocks: [
      "Persönliche Einleitung mit Projektbezug",
      "Projekt- oder Einheit-Update",
      "Kalender-CTA für Besichtigung",
      "Kontaktperson und Antwortmöglichkeit",
    ],
    personalizationFields: ["contact_first_name", "project_name", "unit_name", "calendar_link"],
  },
  {
    id: "template_seller_valuation",
    workspaceId: workspace.id,
    name: "Eigentümer-Bewertung",
    category: "Bewertung",
    language: "de",
    status: "bereit",
    subjectPattern: "Was ist Ihre Immobilie in {{city}} aktuell wert?",
    previewPattern: "Bewertung, Verkaufszeitpunkt und nächste Schritte kompakt erklärt.",
    blocks: [
      "Marktimpuls nach Stadt",
      "Bewertungs-Checkliste",
      "Antwort-CTA für Rückruf",
      "Consent- und Datenschutz-Hinweis",
    ],
    personalizationFields: ["contact_first_name", "city", "property_type", "callback_link"],
  },
  {
    id: "template_investment_briefing",
    workspaceId: workspace.id,
    name: "Investment-Briefing",
    category: "Investment",
    language: "de",
    status: "bereit",
    subjectPattern: "{{city}} Investment: Rendite, Lage und Vermietbarkeit",
    previewPattern: "Drei Punkte, die vor dem nächsten Investment-Call wichtig sind.",
    blocks: [
      "Renditeannahmen",
      "Budget- und Risikoprofil",
      "Teams-Termin CTA",
      "Nächster Deal-Schritt",
    ],
    personalizationFields: ["contact_first_name", "city", "budget", "teams_link"],
  },
  {
    id: "template_reactivation",
    workspaceId: workspace.id,
    name: "Reaktivierung warmer Kontakte",
    category: "Reaktivierung",
    language: "de",
    status: "entwurf",
    subjectPattern: "Sind Immobilienprojekte für Sie noch relevant?",
    previewPattern: "Ein kurzer Abgleich, damit Sie nur passende Updates erhalten.",
    blocks: [
      "Kurzer Relevanz-Check",
      "Interessenpräferenz",
      "Preference-Center Hinweis",
      "Abmelde- und Datenschutz-Hinweis",
    ],
    personalizationFields: ["contact_first_name", "preference_center_url"],
  },
];

export const newsletterSegments: NewsletterSegment[] = [
  {
    id: "segment_buyer_graz",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Käufer Graz mit Besichtigungsinteresse",
    audience: "Käufer",
    language: "de",
    source: "Funnel",
    contacts: 126,
    optIns: 84,
    health: "bereit",
    rules: [
      "Newsletter Opt-in vorhanden",
      "Interesse an Neubau oder 3-Zimmer-Wohnung",
      "Projekt Wohnpark Graz zugeordnet",
    ],
    resendAudienceId: "aud_buyer_graz",
  },
  {
    id: "segment_seller_linz",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    name: "Eigentümer Linz Verkaufsabsicht",
    audience: "Verkäufer",
    language: "de",
    source: "CRM",
    contacts: 104,
    optIns: 61,
    health: "prüfen",
    rules: [
      "WhatsApp oder Telefon Consent prüfen",
      "Verkaufszeitraum unter 12 Monate",
      "Objektdaten zumindest teilweise vorhanden",
    ],
    resendAudienceId: "aud_seller_linz",
  },
  {
    id: "segment_investors_wien",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Investoren Wien Renditeprofil",
    audience: "Investor",
    language: "de",
    source: "Funnel",
    contacts: 64,
    optIns: 39,
    health: "wachstum",
    rules: [
      "Budget ab 450.000 Euro",
      "Interesse an Vermietung oder Rendite",
      "Instagram oder Website Quelle",
    ],
    resendAudienceId: "aud_investors_wien",
  },
  {
    id: "segment_workspace_digest",
    workspaceId: workspace.id,
    name: "Workspace Newsletter Allgemein",
    audience: "Alle",
    language: "de",
    source: "Resend",
    contacts: 812,
    optIns: 812,
    health: "bereit",
    rules: [
      "Globaler Newsletter Opt-in",
      "Keine Projektbindung",
      "Sprache Deutsch als Standard",
    ],
    resendAudienceId: "aud_workspace_general",
  },
];

export const newsletterCampaigns: NewsletterCampaign[] = [
  {
    id: "campaign_wohnpark_b12",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    segmentId: "segment_buyer_graz",
    templateId: "template_project_update",
    name: "Wohnpark Graz Einheit B12 Update",
    fromName: "Novalure Immobilien",
    fromEmail: "newsletter@novalure.eu",
    replyTo: "graz@novalure.local",
    subject: "Neue Informationen zur Einheit B12 im Wohnpark Graz",
    previewText: "Grundriss, Besichtigung und Reservierungsfenster für interessierte Käufer.",
    status: "geplant",
    goal: "Besichtigungstermine für qualifizierte Käufer erhöhen.",
    recipients: 84,
    sendAt: "2026-05-13T09:30:00+02:00",
    contentBlocks: [
      "Projekt-Update und verfügbare Einheiten",
      "Besichtigungsfenster mit Microsoft 365 Kalenderlink",
      "Antwort-CTA für Rückfragen an Sales Graz",
    ],
    ownerUserId: "user_sales_graz",
    utmCampaign: "wohnpark_b12_update",
    abTest: {
      variantA: "Neue Informationen zur Einheit B12 im Wohnpark Graz",
      variantB: "Wohnpark Graz: Ist Einheit B12 passend für Sie?",
      testSizePercent: 20,
      winnerMetric: "click",
    },
  },
  {
    id: "campaign_seller_linz_value",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    segmentId: "segment_seller_linz",
    templateId: "template_seller_valuation",
    name: "Eigentümer Linz Bewertungsimpuls",
    fromName: "Franz von Novalure",
    fromEmail: "franz@novalure.eu",
    replyTo: "franz@novalure.local",
    subject: "Was ist Ihre Wohnung in Linz aktuell wert?",
    previewText: "Kurzbewertung, Verkaufszeitpunkt und nächste Schritte für Eigentümer.",
    status: "entwurf",
    goal: "Bewertungsgespräche aus warmen Eigentümer-Leads erzeugen.",
    recipients: 61,
    contentBlocks: [
      "Marktimpuls Linz kompakt",
      "Checkliste für Verkaufsabsicht",
      "WhatsApp Rückfrage mit Consent-Hinweis",
    ],
    ownerUserId: "user_franz",
    utmCampaign: "seller_linz_valuation",
  },
  {
    id: "campaign_investment_yield",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    segmentId: "segment_investors_wien",
    templateId: "template_investment_briefing",
    name: "Investment Wien Renditebriefing",
    fromName: "Novalure Investment",
    fromEmail: "investment@novalure.eu",
    replyTo: "franz@novalure.local",
    subject: "Investmentprofil Wien: Rendite, Lage und Vermietbarkeit",
    previewText: "Drei Punkte, die Investoren vor dem nächsten Call prüfen sollten.",
    status: "bereit",
    goal: "Investment-Calls vorbereiten und Budgetqualität erhöhen.",
    recipients: 39,
    sendAt: "2026-05-12T08:00:00+02:00",
    contentBlocks: [
      "Renditeannahmen erklären",
      "Budget und Haltedauer abfragen",
      "Teams-Termin für Investment-Call anbieten",
    ],
    ownerUserId: "user_franz",
    utmCampaign: "investment_wien_yield",
    abTest: {
      variantA: "Investmentprofil Wien: Rendite, Lage und Vermietbarkeit",
      variantB: "Wien-Investment: passt dieses Profil zu Ihrer Strategie?",
      testSizePercent: 30,
      winnerMetric: "open",
    },
  },
  {
    id: "campaign_workspace_monthly",
    workspaceId: workspace.id,
    segmentId: "segment_workspace_digest",
    templateId: "template_reactivation",
    name: "Novalure Monatsupdate",
    fromName: "Novalure",
    fromEmail: "newsletter@novalure.eu",
    replyTo: "hello@novalure.eu",
    subject: "Neue Projekte, Marktchancen und Immobilien-Updates",
    previewText: "Ein kompakter Überblick über aktuelle Chancen und nächste Termine.",
    status: "gesendet",
    goal: "Bestandskontakte reaktivieren und Projektinteresse messen.",
    recipients: 812,
    sendAt: "2026-05-01T10:00:00+02:00",
    openRate: 42.8,
    clickRate: 7.4,
    bounceRate: 0.4,
    unsubscribeRate: 0.2,
    contentBlocks: [
      "Projektüberblick",
      "Top-Immobilien und Marktimpuls",
      "CTA zur Projektberatung",
    ],
    ownerUserId: "user_franz",
    utmCampaign: "workspace_monthly_update",
  },
];

export const newsletterAutomations: NewsletterAutomation[] = [
  {
    id: "newsletter_auto_welcome_buyer",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Willkommensserie Käufer Graz",
    trigger: "Kontakt tritt Segment Käufer Graz bei",
    segmentId: "segment_buyer_graz",
    status: "aktiv",
    goal: "Neue Käufer innerhalb von 48 Stunden zum Besichtigungstermin führen.",
    steps: [
      { delay: "Sofort", channel: "Email", action: "Projektupdate und verfügbare Einheiten senden" },
      { delay: "1 Tag", channel: "Aufgabe", action: "Hot Lead prüfen und Rückruf vorbereiten" },
      { delay: "2 Tage", channel: "Email", action: "Besichtigungsfenster und Kalenderlink nachfassen" },
    ],
  },
  {
    id: "newsletter_auto_seller_reactivation",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    name: "Eigentümer Reaktivierung",
    trigger: "Kein Kontakt seit 14 Tagen und Verkaufszeitraum unter 12 Monate",
    segmentId: "segment_seller_linz",
    status: "entwurf",
    goal: "Warme Eigentümer in Bewertungsgespräche zurückholen.",
    steps: [
      { delay: "Sofort", channel: "Email", action: "Bewertungsimpuls senden" },
      { delay: "2 Tage", channel: "WhatsApp", action: "Kurze Rückfrage mit Consent prüfen" },
      { delay: "3 Tage", channel: "Aufgabe", action: "Persönlichen Rückruf einplanen" },
    ],
  },
  {
    id: "newsletter_auto_investor_briefing",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Investment Briefing vor Call",
    trigger: "Investment-Call im Kalender gebucht",
    segmentId: "segment_investors_wien",
    status: "aktiv",
    goal: "Investoren vor dem Termin qualifizieren und bessere Gespräche führen.",
    steps: [
      { delay: "24 Stunden vorher", channel: "Email", action: "Renditebriefing senden" },
      { delay: "2 Stunden vorher", channel: "Aufgabe", action: "Budget und Fragen im CRM prüfen" },
    ],
  },
];

export const leadSequences: LeadSequenceDefinition[] = [
  {
    id: "sequence_buyer_expose_followup",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Käufer Expose Follow-up",
    audience: "Käufer",
    goal: "Exposes schnell zustellen und stille Käufer innerhalb von 7 Tagen zu einem Besichtigungstermin führen.",
    trigger: "document_sent",
    status: "active",
    businessHours: "Mo-Fr 08:00-18:30",
    maxTouchpoints14Days: 4,
    minHoursBetweenTouches: 24,
    steps: [
      {
        id: "sequence_step_expose_email",
        sequenceId: "sequence_buyer_expose_followup",
        position: 1,
        title: "Expose sofort senden",
        delayLabel: "Sofort",
        delayHours: 0,
        channel: "email",
        action: "Expose-Link, Projektkurzinfo und klaren Termin-CTA senden.",
        ownerMode: "contact_owner",
        conditions: ["email_available"],
        stopRules: ["opt_out", "bounce", "manual_pause"],
        templateSubject: "Ihr Expose zu {{property.name}}",
        templateBody:
          "Hallo {{contact.firstName}}, hier ist das angefragte Expose. Wenn die Einheit passt, können Sie direkt einen Besichtigungstermin wählen.",
      },
      {
        id: "sequence_step_hot_lead_task",
        sequenceId: "sequence_buyer_expose_followup",
        position: 2,
        title: "Hot Lead prüfen",
        delayLabel: "Sofort intern",
        delayHours: 0,
        channel: "task",
        action: "Budget, Finanzierung und Wunschlage prüfen; bei Score über 75 Rückruf vorbereiten.",
        ownerMode: "contact_owner",
        conditions: ["high_score"],
        stopRules: ["manual_pause"],
        taskPriority: "Hoch",
      },
      {
        id: "sequence_step_opened_followup",
        sequenceId: "sequence_buyer_expose_followup",
        position: 3,
        title: "Besichtigung vorschlagen",
        delayLabel: "Nach 24 Stunden",
        delayHours: 24,
        channel: "email",
        action: "Wenn das Expose geöffnet wurde, passende Besichtigungsfenster und Kalenderlink senden.",
        ownerMode: "contact_owner",
        conditions: ["document_opened", "meeting_not_booked", "no_reply"],
        stopRules: ["reply_received", "meeting_booked", "opt_out", "bounce", "deal_won", "deal_lost", "manual_pause"],
        templateSubject: "Passt {{property.name}} für eine Besichtigung?",
      },
      {
        id: "sequence_step_not_opened_task",
        sequenceId: "sequence_buyer_expose_followup",
        position: 4,
        title: "Zustellung klären",
        delayLabel: "Nach 48 Stunden",
        delayHours: 48,
        channel: "call",
        action: "Wenn das Expose nicht geöffnet wurde, Telefonnummer oder E-Mail prüfen und kurzen Rückruf einplanen.",
        ownerMode: "contact_owner",
        conditions: ["document_not_opened", "no_reply"],
        stopRules: ["reply_received", "meeting_booked", "opt_out", "deal_won", "deal_lost", "manual_pause"],
        taskPriority: "Mittel",
      },
      {
        id: "sequence_step_whatsapp_nudge",
        sequenceId: "sequence_buyer_expose_followup",
        position: 5,
        title: "WhatsApp Kurzfrage",
        delayLabel: "Nach 72 Stunden",
        delayHours: 72,
        channel: "whatsapp",
        action: "Nur mit Consent oder aktivem WhatsApp-Kontext fragen, ob zwei Besichtigungstermine geschickt werden sollen.",
        ownerMode: "contact_owner",
        conditions: ["whatsapp_allowed", "no_reply", "meeting_not_booked"],
        stopRules: ["reply_received", "meeting_booked", "opt_out", "deal_won", "deal_lost", "manual_pause"],
        templateBody: "Hallo {{contact.firstName}}, soll ich Ihnen zwei passende Besichtigungstermine schicken?",
      },
      {
        id: "sequence_step_pause_later",
        sequenceId: "sequence_buyer_expose_followup",
        position: 6,
        title: "Letztes Follow-up",
        delayLabel: "Nach 7 Tagen",
        delayHours: 168,
        channel: "email",
        action: "Letzte kurze Nachfrage senden und Deal danach auf Nachfassen später setzen.",
        ownerMode: "contact_owner",
        conditions: ["no_reply", "meeting_not_booked"],
        stopRules: ["reply_received", "meeting_booked", "opt_out", "bounce", "deal_won", "deal_lost", "manual_pause"],
        templateSubject: "Soll ich Ihr Interesse vormerken?",
      },
    ],
  },
  {
    id: "sequence_seller_valuation",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    name: "Verkäufer Bewertung",
    audience: "Verkäufer",
    goal: "Bewertungsanfragen absichern, Unterlagen sammeln und persoenlichen Termin buchen.",
    trigger: "funnel_submitted",
    status: "draft",
    businessHours: "Mo-Fr 08:00-18:30",
    maxTouchpoints14Days: 4,
    minHoursBetweenTouches: 24,
    steps: [
      {
        id: "sequence_step_seller_ack",
        sequenceId: "sequence_seller_valuation",
        position: 1,
        title: "Anfrage bestätigen",
        delayLabel: "Sofort",
        delayHours: 0,
        channel: "email",
        action: "Eingang bestätigen und fehlende Eckdaten zur Immobilie abfragen.",
        ownerMode: "project_owner",
        conditions: ["email_available"],
        stopRules: ["opt_out", "bounce", "manual_pause"],
        templateSubject: "Ihre Immobilienbewertung ist in Vorbereitung",
      },
      {
        id: "sequence_step_seller_call",
        sequenceId: "sequence_seller_valuation",
        position: 2,
        title: "Bewertungsgespräch",
        delayLabel: "Nach 4 Stunden",
        delayHours: 4,
        channel: "call",
        action: "Eigentümer anrufen, Verkaufszeitraum klären und Bewertungstermin vorschlagen.",
        ownerMode: "contact_owner",
        conditions: ["high_score", "no_reply"],
        stopRules: ["reply_received", "meeting_booked", "manual_pause"],
        taskPriority: "Hoch",
      },
      {
        id: "sequence_step_seller_docs",
        sequenceId: "sequence_seller_valuation",
        position: 3,
        title: "Unterlagen anfordern",
        delayLabel: "Nach 1 Tag",
        delayHours: 24,
        channel: "email",
        action: "Grundbuch, Pläne, Betriebskosten und Fotos als nächste Unterlagen anfordern.",
        ownerMode: "contact_owner",
        conditions: ["no_reply"],
        stopRules: ["reply_received", "meeting_booked", "opt_out", "bounce", "manual_pause"],
      },
    ],
  },
  {
    id: "sequence_investor_briefing",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Investor Briefing",
    audience: "Investor",
    goal: "Investmentprofil schaerfen und Call mit relevanten Unterlagen vorbereiten.",
    trigger: "meeting_booked",
    status: "active",
    businessHours: "Mo-Fr 08:00-18:30",
    maxTouchpoints14Days: 3,
    minHoursBetweenTouches: 24,
    steps: [
      {
        id: "sequence_step_investor_brief",
        sequenceId: "sequence_investor_briefing",
        position: 1,
        title: "Renditebriefing senden",
        delayLabel: "24 Stunden vorher",
        delayHours: -24,
        channel: "email",
        action: "Freigegebene Investmentunterlagen und Agenda für den Call senden.",
        ownerMode: "contact_owner",
        conditions: ["email_available"],
        stopRules: ["meeting_booked", "opt_out", "bounce", "manual_pause"],
        templateSubject: "Vorbereitung für Ihren Investment-Call",
      },
      {
        id: "sequence_step_investor_internal",
        sequenceId: "sequence_investor_briefing",
        position: 2,
        title: "Profil prüfen",
        delayLabel: "2 Stunden vorher",
        delayHours: -2,
        channel: "task",
        action: "Budget, Renditeerwartung und passende Objekte im CRM prüfen.",
        ownerMode: "contact_owner",
        conditions: ["always"],
        stopRules: ["manual_pause"],
        taskPriority: "Mittel",
      },
    ],
  },
  {
    id: "sequence_viewing_followup",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Besichtigung Follow-up",
    audience: "Käufer",
    goal: "Nach Besichtigungen Feedback erfassen und nächsten Deal-Schritt sichern.",
    trigger: "meeting_booked",
    status: "active",
    businessHours: "Mo-Fr 08:00-18:30",
    maxTouchpoints14Days: 4,
    minHoursBetweenTouches: 24,
    steps: [
      {
        id: "sequence_step_viewing_confirm",
        sequenceId: "sequence_viewing_followup",
        position: 1,
        title: "Terminbestätigung",
        delayLabel: "Sofort",
        delayHours: 0,
        channel: "calendar",
        action: "Kalenderbestätigung und Reminder über die bestehende Meeting-Automation senden.",
        ownerMode: "contact_owner",
        conditions: ["always"],
        stopRules: ["manual_pause", "opt_out"],
      },
      {
        id: "sequence_step_viewing_feedback",
        sequenceId: "sequence_viewing_followup",
        position: 2,
        title: "Feedback einholen",
        delayLabel: "2 Stunden danach",
        delayHours: 2,
        channel: "email",
        action: "Feedback, Einwände und Reservierungsinteresse abfragen.",
        ownerMode: "contact_owner",
        conditions: ["meeting_not_booked"],
        stopRules: ["reply_received", "deal_won", "deal_lost", "opt_out", "manual_pause"],
        templateSubject: "Wie war die Besichtigung?",
      },
    ],
  },
];

export const leadSequenceEvents: LeadSequenceEvent[] = [
  {
    id: "sequence_event_mira_document_sent",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_mira_klein",
    leadId: "lead_mira_klein",
    sequenceId: "sequence_buyer_expose_followup",
    stepId: "sequence_step_expose_email",
    type: "document_sent",
    occurredAt: "2026-05-10T17:52:00+02:00",
    detail: "Expose Einheit B12 per E-Mail gesendet.",
  },
  {
    id: "sequence_event_mira_document_opened",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_mira_klein",
    leadId: "lead_mira_klein",
    sequenceId: "sequence_buyer_expose_followup",
    stepId: "sequence_step_opened_followup",
    type: "document_opened",
    occurredAt: "2026-05-10T19:10:00+02:00",
    detail: "Expose-Link geöffnet, noch kein neuer Termin gebucht.",
  },
  {
    id: "sequence_event_daniel_document_sent",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    contactId: "contact_daniel_hofer",
    leadId: "lead_daniel_hofer",
    sequenceId: "sequence_investor_briefing",
    stepId: "sequence_step_investor_brief",
    type: "email_sent",
    occurredAt: "2026-05-11T09:00:00+02:00",
    detail: "Investment-Briefing für den Call vorbereitet.",
  },
];

export const newsletterDeliverability: NewsletterDeliverability[] = [
  {
    id: "deliverability_novalure_main",
    workspaceId: workspace.id,
    domain: "novalure.eu",
    fromEmail: "newsletter@novalure.eu",
    status: "bereit",
    spf: "ok",
    dkim: "ok",
    dmarc: "ok",
    bounceRate: 0.4,
    complaintRate: 0.03,
    reputationScore: 94,
  },
  {
    id: "deliverability_novalure_investment",
    workspaceId: workspace.id,
    domain: "novalure.eu",
    fromEmail: "investment@novalure.eu",
    status: "prüfen",
    spf: "ok",
    dkim: "ok",
    dmarc: "prüfen",
    bounceRate: 0.8,
    complaintRate: 0.05,
    reputationScore: 87,
  },
];

export const newsletterSuppressions: NewsletterSuppression[] = [
  {
    id: "suppression_old_bounce",
    workspaceId: workspace.id,
    email: "old.lead@demo.novalure-crm.app",
    reason: "bounce",
    source: "Resend",
    capturedAt: "2026-05-04T10:12:00+02:00",
  },
  {
    id: "suppression_unsubscribe",
    workspaceId: workspace.id,
    email: "abmeldung@demo.novalure-crm.app",
    reason: "unsubscribe",
    source: "Preference Center",
    capturedAt: "2026-05-08T18:30:00+02:00",
  },
];

export const consents: ConsentRecord[] = [
  {
    id: "consent_anna_whatsapp",
    workspaceId: workspace.id,
    contactId: "contact_anna_berger",
    projectId: "project_seller_linz",
    channel: "WhatsApp",
    status: "Opt-in",
    source: "WhatsApp Bot",
    capturedAt: "2026-05-11T09:20:00+02:00",
  },
  {
    id: "consent_mira_newsletter",
    workspaceId: workspace.id,
    contactId: "contact_mira_klein",
    projectId: "project_wohnpark_graz",
    channel: "Newsletter",
    status: "Opt-in",
    source: "Website Funnel",
    capturedAt: "2026-05-10T17:45:00+02:00",
  },
  {
    id: "consent_daniel_crm",
    workspaceId: workspace.id,
    contactId: "contact_daniel_hofer",
    projectId: "project_investment_wien",
    channel: "Instagram",
    status: "Nur CRM",
    source: "Instagram DM",
    capturedAt: "2026-05-11T08:10:00+02:00",
  },
];

export const conversations: Conversation[] = [
  {
    id: "conversation_anna_whatsapp",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    contactId: "contact_anna_berger",
    leadId: "lead_anna_berger",
    channel: "WhatsApp",
    direction: "inbound",
    summary: "Möchte Verkaufspreis und Ablauf für Eigentumswohnung in Linz einschätzen.",
    sentiment: "hot",
    lastMessageAt: "2026-05-11T09:22:00+02:00",
  },
  {
    id: "conversation_mira_website",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    contactId: "contact_mira_klein",
    leadId: "lead_mira_klein",
    channel: "Website Bot",
    direction: "inbound",
    summary: "Interessiert sich für Einheit B12, Finanzierung ist laut Formular vorgeprüft.",
    sentiment: "hot",
    lastMessageAt: "2026-05-10T17:48:00+02:00",
  },
  {
    id: "conversation_daniel_instagram",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    contactId: "contact_daniel_hofer",
    leadId: "lead_daniel_hofer",
    channel: "Instagram",
    direction: "inbound",
    summary: "Fragt nach Investmentobjekten ab 450.000 Euro und Renditeannahmen.",
    sentiment: "warm",
    lastMessageAt: "2026-05-11T08:13:00+02:00",
  },
];

export const contactTimeline: ContactTimelineItem[] = [
  {
    id: "timeline_anna_whatsapp",
    workspaceId: workspace.id,
    contactId: "contact_anna_berger",
    organizationId: "org_berger_family",
    projectId: "project_seller_linz",
    channel: "WhatsApp",
    title: "WhatsApp Anfrage eingegangen",
    detail: "Verkaufspreis und Ablauf für Eigentumswohnung in Linz einschätzen.",
    occurredAt: "2026-05-11T09:22:00+02:00",
    outcome: "offen",
  },
  {
    id: "timeline_anna_task",
    workspaceId: workspace.id,
    contactId: "contact_anna_berger",
    organizationId: "org_berger_family",
    projectId: "project_seller_linz",
    channel: "Aufgabe",
    title: "Rückruf fällig",
    detail: "Kontakt vor Ablauf des Speed-to-Lead Fensters anrufen.",
    occurredAt: "2026-05-11T14:30:00+02:00",
    outcome: "risiko",
  },
  {
    id: "timeline_mira_website",
    workspaceId: workspace.id,
    contactId: "contact_mira_klein",
    organizationId: "org_klein_household",
    projectId: "project_wohnpark_graz",
    channel: "Website Bot",
    title: "Website Bot Qualifizierung",
    detail: "Einheit B12, Finanzierung vorgeprüft, Besichtigung als nächster Schritt.",
    occurredAt: "2026-05-10T17:48:00+02:00",
    outcome: "info",
  },
  {
    id: "timeline_daniel_instagram",
    workspaceId: workspace.id,
    contactId: "contact_daniel_hofer",
    organizationId: "org_hofer_invest",
    projectId: "project_investment_wien",
    channel: "Instagram",
    title: "Instagram Investment-Anfrage",
    detail: "Fragt nach Renditeannahmen und Investmentobjekten ab 450.000 Euro.",
    occurredAt: "2026-05-11T08:13:00+02:00",
    outcome: "offen",
  },
  {
    id: "timeline_thomas_meeting",
    workspaceId: workspace.id,
    contactId: "contact_thomas_reiter",
    organizationId: "org_reiter_development",
    projectId: "project_wohnpark_graz",
    channel: "Microsoft 365",
    title: "Projektgespräch geplant",
    detail: "Teams-Link und Unterlagen für Bauträger-Termin prüfen.",
    occurredAt: "2026-05-12T09:00:00+02:00",
    outcome: "offen",
  },
];

export const automations: Automation[] = [
  {
    id: "automation_whatsapp_bot",
    workspaceId: workspace.id,
    name: "WhatsApp Bot",
    channel: "WhatsApp",
    status: "Bereit",
    detail: "Antwortet nur mit freigegebenem Projektwissen.",
  },
  {
    id: "automation_instagram_qualifier",
    workspaceId: workspace.id,
    name: "Instagram Qualifier",
    channel: "Instagram",
    status: "Training",
    detail: "Fragt Budget, Lage und Zeithorizont ab.",
  },
  {
    id: "automation_microsoft_calendar",
    workspaceId: workspace.id,
    name: "Microsoft Kalender",
    channel: "Microsoft 365",
    status: "Verbinden",
    detail: "Erstellt Termine und Teams-Meetings pro Projekt.",
  },
  {
    id: "automation_resend_newsletter",
    workspaceId: workspace.id,
    name: "Resend Newsletter",
    channel: "E-Mail",
    status: "Geplant",
    detail: "Segmentiert Opt-ins nach Projekt und Lead-Typ.",
  },
];

export const crmBotTools: CrmBotTool[] = [
  {
    id: "tool_load_conversation_history",
    name: "load_conversation_history",
    description: "Loads recent CRM conversation context before the bot answers.",
    riskLevel: "low",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_qualify_lead",
    name: "qualify_lead",
    description: "Scores need, budget, timing and fit for routing.",
    riskLevel: "medium",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_research_lead",
    name: "research_lead",
    description: "Creates a compact research brief for sales review.",
    riskLevel: "medium",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_search_knowledge",
    name: "search_approved_knowledge",
    description: "Searches reviewed knowledge chunks and returns citations.",
    riskLevel: "low",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_capture_customer_data",
    name: "capture_customer_data",
    description: "Captures name, contact channel, intent, consent and CRM-ready customer fields.",
    riskLevel: "medium",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_find_meeting_slots",
    name: "find_meeting_slots",
    description: "Finds available meeting slots from connected meeting pages and calendars.",
    riskLevel: "medium",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_book_meeting",
    name: "book_meeting",
    description: "Books a meeting after the customer selected a slot and contact data is available.",
    riskLevel: "high",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_send_document",
    name: "send_document",
    description: "Prepares approved exposes, offers or PDFs for channel-specific delivery.",
    riskLevel: "high",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_send_channel_reply",
    name: "send_channel_reply",
    description: "Prepares replies for Webchat, WhatsApp, Instagram, Messenger, email or webhooks.",
    riskLevel: "medium",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_send_whatsapp_template",
    name: "send_whatsapp_template",
    description: "Prepares approved WhatsApp template messages outside the service window.",
    riskLevel: "high",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_create_email_draft",
    name: "create_email_draft",
    description: "Creates follow-up email drafts and logs them for policy review.",
    riskLevel: "medium",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_create_deal",
    name: "create_deal",
    description: "Creates or prepares a deal from a qualified lead when policy checks pass.",
    riskLevel: "high",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_analyze_call_transcript",
    name: "analyze_call_transcript",
    description: "Turns call transcripts into summary, objections, tasks and deal signals.",
    riskLevel: "low",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
  {
    id: "tool_escalate_to_human",
    name: "escalate_to_human",
    description: "Hands sensitive or uncertain conversations to a team.",
    riskLevel: "medium",
    requiresHumanApproval: false,
    auditLogEnabled: true,
    enabled: true,
  },
];

export const crmBots: CrmBot[] = [
  {
    id: "bot_sales_qualifier",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Omnichannel Sales Concierge",
    description:
      "Communicates through Webchat, WhatsApp, Instagram and Messenger, uses approved knowledge, captures customer data, prepares documents and routes qualified leads to meetings.",
    role: "sales_qualifier",
    status: "active",
    audience: "Website, WhatsApp, Instagram and Messenger leads",
    language: "auto",
    tone: "clear, helpful, conservative",
    answerLength: "normal",
    brandVoice: "Professional real estate advisory",
    strictKnowledge: true,
    modelConfig: {
      primaryModel: "openai/gpt-5.4",
      fallbackModel: "openai/gpt-5.4-mini",
      temperature: 0.3,
      maxSteps: 5,
      costTag: "sales-qualifier",
    },
    channels: [
      {
        id: "bot_sales_qualifier_webchat",
        channel: "Webchat",
        active: true,
        greetingEn: "Hi, I can help qualify your interest and prepare the next step.",
        greetingDe: "Hallo, ich helfe bei der Einordnung Ihrer Anfrage und bereite den nächsten Schritt vor.",
        handoffRules: ["price negotiation", "legal questions", "low confidence", "customer asks for a human"],
        businessHours: "Mon-Fri 09:00-18:00 Europe/Vienna",
        complianceNote: "Consent, domain allowlist and transcript storage are checked before publishing.",
        inboundMode: "Novalure Widget Event",
        outboundMode: "Streaming Chat-Antwort",
        language: "auto",
        provider: "Novalure Webchat",
        setupStatus: "connected",
        setupSteps: ["Widget-Code kopieren", "Domain freigeben", "Testnachricht senden"],
        targetTeam: "Sales Graz",
        webhookPath: "/api/bots/chat",
      },
      {
        id: "bot_sales_qualifier_whatsapp",
        channel: "WhatsApp",
        active: true,
        greetingEn: "Thanks for your message. I can check the project details and prepare an appointment.",
        greetingDe: "Danke für Ihre Nachricht. Ich prüfe die Projektdetails und bereite bei Bedarf einen Termin vor.",
        handoffRules: ["outside 24h service window", "contract questions", "customer asks for human"],
        businessHours: "Always on with approval rules",
        complianceNote: "24h service window is respected; proactive messages use approved templates only.",
        inboundMode: "Meta WhatsApp Webhook",
        outboundMode: "24h Antwort oder Template",
        language: "auto",
        provider: "WhatsApp Business Platform",
        setupStatus: "needs_review",
        setupSteps: ["Business-Konto verbinden", "Webhook verifizieren", "Templates hinterlegen"],
        targetTeam: "Sales Graz",
        webhookPath: "/api/bots/channels/webhook",
      },
      {
        id: "bot_sales_qualifier_instagram",
        channel: "Instagram",
        active: false,
        greetingEn: "I can answer project questions and move qualified enquiries into CRM.",
        greetingDe: "Ich beantworte Projektfragen und übergebe qualifizierte Anfragen ins CRM.",
        handoffRules: ["negative sentiment", "lead wants callback", "missing opt-in"],
        businessHours: "Mon-Fri 09:00-18:00 Europe/Vienna",
        complianceNote: "Instagram Business connection and human handoff must be tested before activation.",
        inboundMode: "Instagram Messaging Webhook",
        outboundMode: "Instagram DM Antwort",
        language: "auto",
        provider: "Instagram Messaging API",
        setupStatus: "not_connected",
        setupSteps: ["Instagram Business verbinden", "Webhook abonnieren", "Handoff testen"],
        targetTeam: "Sales Graz",
        webhookPath: "/api/bots/channels/webhook",
      },
      {
        id: "bot_sales_qualifier_messenger",
        channel: "Facebook Messenger",
        active: false,
        greetingEn: "I can qualify the enquiry and prepare the next CRM step.",
        greetingDe: "Ich qualifiziere die Anfrage und bereite den nächsten CRM-Schritt vor.",
        handoffRules: ["low confidence", "sensitive data", "customer asks for human"],
        businessHours: "Mon-Fri 09:00-18:00 Europe/Vienna",
        complianceNote: "Facebook Page messaging permissions and escalation path are required.",
        inboundMode: "Messenger Webhook",
        outboundMode: "Messenger Antwort",
        language: "auto",
        provider: "Messenger Platform",
        setupStatus: "not_connected",
        setupSteps: ["Facebook Page verbinden", "Webhook abonnieren", "Inbox-Handoff testen"],
        targetTeam: "Sales Graz",
        webhookPath: "/api/bots/channels/webhook",
      },
    ],
    tools: crmBotTools.filter((tool) =>
      [
        "tool_load_conversation_history",
        "tool_search_knowledge",
        "tool_capture_customer_data",
        "tool_qualify_lead",
        "tool_find_meeting_slots",
        "tool_book_meeting",
        "tool_send_document",
        "tool_send_channel_reply",
        "tool_send_whatsapp_template",
        "tool_create_email_draft",
        "tool_create_deal",
        "tool_escalate_to_human",
      ].includes(tool.id),
    ),
    setupChecklist: botSelfServeSetup.map((step, index) => ({
      done: index < 3,
      label: step.label,
      owner: step.owner,
    })),
    actionPolicies: [
      {
        action: "Antwort senden",
        approval: "audit",
        rule: "Normale Antworten dürfen direkt gesendet werden, solange sie auf freigegebenem Wissen basieren.",
      },
      {
        action: "Kundendaten aufnehmen",
        approval: "audit",
        rule: "Name, Kontaktweg, Bedarf und Einwilligung werden protokolliert und im CRM vorbereitet.",
      },
      {
        action: "Dokument oder Expose senden",
        approval: "optional",
        rule: "Dokumente dürfen direkt rausgehen, wenn sie freigegeben sind und eine öffentliche URL haben.",
      },
      {
        action: "Termin buchen",
        approval: "optional",
        rule: "Der Bot darf buchen, wenn Terminseite, Datum, Slot und Kontaktdaten eindeutig sind.",
      },
      {
        action: "Verbotene Aussagen blockieren",
        approval: "required",
        rule: "Garantierte Renditen, verbindliche Rechts-/Steuerauskunft, Finanzierungszusagen und Preisgarantien werden hart blockiert.",
      },
    ],
    documentLibrary: [
      {
        approvalRequired: false,
        id: "doc_wohnpark_graz_expose",
        name: "Wohnpark Graz Expose",
        status: "approved",
        type: "expose",
      },
      {
        approvalRequired: true,
        id: "doc_financing_checklist",
        name: "Finanzierungs-Checkliste",
        status: "needs_review",
        type: "checklist",
      },
    ],
    createdAt: "2026-05-12T09:00:00+02:00",
    updatedAt: "2026-05-14T10:20:00+02:00",
  },
  {
    id: "bot_call_intelligence",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Call Intelligence Agent",
    description: "Extracts summary, objections, action items, deal signals and knowledge gaps from call transcripts.",
    role: "crm_data_agent",
    status: "test",
    audience: "Sales and investment advisory calls",
    language: "auto",
    tone: "precise and evidence-based",
    answerLength: "detailed",
    brandVoice: "Operational CRM analyst",
    strictKnowledge: false,
    modelConfig: {
      primaryModel: "openai/gpt-5.4",
      fallbackModel: "openai/gpt-5.4-mini",
      temperature: 0.2,
      maxSteps: 4,
      costTag: "call-intelligence",
    },
    channels: [
      {
        id: "bot_call_intelligence_upload",
        channel: "API/Webhook",
        active: true,
        greetingEn: "Upload a transcript to prepare call insights.",
        greetingDe: "Laden Sie ein Transkript hoch, um Call-Insights vorzubereiten.",
        handoffRules: ["crm update requires approval", "knowledge gap detected"],
        businessHours: "Always on",
        complianceNote: "Webhook payloads require signed delivery and are stored with audit trail.",
        inboundMode: "Signed POST Payload",
        outboundMode: "Webhook Callback",
        language: "auto",
        provider: "Novalure Webhook",
        setupStatus: "connected",
        setupSteps: ["Endpoint kopieren", "Secret setzen", "Testpayload senden"],
        targetTeam: "Operations",
        webhookPath: "/api/bots/channels/webhook",
      },
    ],
    tools: crmBotTools.filter((tool) =>
      ["tool_analyze_call_transcript", "tool_create_deal", "tool_escalate_to_human"].includes(tool.id),
    ),
    createdAt: "2026-05-12T10:15:00+02:00",
    updatedAt: "2026-05-12T13:35:00+02:00",
  },
];

export const crmBotConversations: CrmBotConversation[] = [
  {
    id: "bot_conversation_mira_website",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    botId: "bot_sales_qualifier",
    contactId: "contact_mira_klein",
    title: "Wohnpark Graz unit B12 qualification",
    status: "open",
    updatedAt: "2026-05-12T11:42:00+02:00",
    messages: [
      {
        id: "bot_message_mira_1",
        role: "user",
        content: "I am interested in unit B12 and want to understand financing options.",
        createdAt: "2026-05-12T11:39:00+02:00",
      },
      {
        id: "bot_message_mira_2",
        role: "assistant",
        content: "I can help with the next step and will only use approved project information before suggesting an appointment.",
        createdAt: "2026-05-12T11:40:00+02:00",
      },
    ],
  },
];

export const botLeadWorkflows: BotLeadWorkflow[] = [
  {
    id: "workflow_hot_lead_review",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Hot lead review and follow-up",
    trigger: "chat_qualified",
    steps: [
      "capture",
      "capture_contact",
      "research",
      "qualify",
      "send_document",
      "book_meeting",
      "draft_email",
      "create_deal",
      "handoff",
    ],
    humanApprovalRequired: false,
    active: true,
    runsToday: 14,
    approvalQueue: 0,
    lastRunAt: "2026-05-12T12:18:00+02:00",
    resultPreview: {
      qualification: "qualified",
      score: 82,
      researchBrief: "Lead has a concrete unit interest, financing intent and near-term appointment fit.",
      nextAction: "Send approved document, offer an appointment window and create the deal when policy checks pass.",
      emailSubject: "Next step for your Wohnpark Graz enquiry",
    },
  },
  {
    id: "workflow_manual_research",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    name: "Manual investor research",
    trigger: "manual",
    steps: ["capture", "research", "qualify", "handoff"],
    humanApprovalRequired: false,
    active: true,
    runsToday: 5,
    approvalQueue: 0,
    lastRunAt: "2026-05-12T10:44:00+02:00",
    resultPreview: {
      qualification: "follow_up",
      score: 68,
      researchBrief: "Investor profile is relevant, but exact yield expectations need confirmation.",
      nextAction: "Ask for yield range and financing status.",
      emailSubject: "Investment criteria for the next proposal",
    },
  },
];

export const botCallInsights: BotCallInsight[] = [
  {
    id: "call_insight_investor_hofer",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    contactId: "contact_daniel_hofer",
    botId: "bot_call_intelligence",
    source: "Zoom",
    summary: "Investor is interested in units above 450,000 EUR, wants clearer yield assumptions and financing scenarios before a second call.",
    sentiment: "high_interest",
    objections: ["Yield assumptions need more evidence", "Financing timeline unclear"],
    actionItems: [
      { title: "Send yield scenario comparison", owner: "Sales Graz", priority: "high" },
      { title: "Confirm financing status", owner: "Franz", priority: "normal" },
    ],
    dealSignals: ["Budget above 450,000 EUR", "Asked for second call", "Requested specific investment scenarios"],
    knowledgeGaps: ["No approved answer for financing partner process", "Yield assumptions need source citation"],
    requiresApproval: false,
    createdAt: "2026-05-12T13:05:00+02:00",
  },
];

export const botLanguageRules: BotLanguageRule[] = [
  {
    id: "bot_language_whatsapp_seller_linz",
    workspaceId: workspace.id,
    projectId: "project_seller_linz",
    channel: "WhatsApp",
    mode: "auto",
    fallbackLanguage: "en",
    detectionSignals: ["chat", "profile", "workspace"],
    confidence: 94,
    promptRule: "Detect the language from the customer message and answer in the same language.",
  },
  {
    id: "bot_language_instagram_investment_wien",
    workspaceId: workspace.id,
    projectId: "project_investment_wien",
    channel: "Instagram",
    mode: "auto",
    fallbackLanguage: "en",
    detectionSignals: ["chat", "form", "workspace"],
    confidence: 88,
    promptRule: "For mixed-language conversations, reply in the customer language used most recently.",
  },
  {
    id: "bot_language_website_graz",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    channel: "Website Bot",
    mode: "auto",
    fallbackLanguage: "en",
    detectionSignals: ["browser", "form", "chat"],
    confidence: 91,
    promptRule: "Use the browser language as the first hint, then prioritize the customer message.",
  },
  {
    id: "bot_language_newsletter_global",
    workspaceId: workspace.id,
    channel: "Newsletter",
    mode: "fixed",
    fallbackLanguage: "en",
    fixedLanguage: "en",
    detectionSignals: ["workspace"],
    confidence: 100,
    promptRule: "Send newsletters in English by default until a segment language is available.",
  },
];

export const knowledgeBase: KnowledgeItem[] = [
  {
    id: "knowledge_wohnpark_expose",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Wohnpark Graz Exposé",
    items: 18,
    coverage: "92%",
    status: "approved",
  },
  {
    id: "knowledge_pricing_units",
    workspaceId: workspace.id,
    projectId: "project_wohnpark_graz",
    name: "Preislisten und Einheiten",
    items: 7,
    coverage: "81%",
    status: "needs-review",
  },
  {
    id: "knowledge_financing",
    workspaceId: workspace.id,
    projectId: "project_novalure_eu",
    name: "Finanzierungsfragen",
    items: 12,
    coverage: "76%",
    status: "needs-review",
  },
];
