/** Display vocabulary only. Stored codes and access semantics remain unchanged. */
const labels: Record<string, readonly [string, string]> = {
  cover: ["Titelbild", "Cover image"],
  exterior: ["Außenansicht", "Exterior"],
  interior: ["Innenansicht", "Interior"],
  floorplan: ["Grundriss", "Floor plan"],
  surroundings: ["Umgebung", "Surroundings"],
  detail: ["Detailaufnahme", "Detail"],
  construction: ["Baufortschritt", "Construction"],
  expose: ["Exposé", "Brochure"],
  energy_certificate: ["Energieausweis", "Energy certificate"],
  land_register: ["Grundbuch", "Land register"],
  contract: ["Vertrag", "Contract"],
  approval: ["Genehmigung", "Permit"],
  proof: ["Nachweis", "Evidence"],
  internal: ["Intern", "Internal"],
  private: ["Privat", "Private"],
  public: ["Öffentlich", "Public"],
  draft: ["Entwurf", "Draft"],
  needs_review: ["Prüfung offen", "Review required"],
  approved: ["Intern freigegeben", "Internally approved"],
  published: ["Veröffentlicht", "Published"],
  sent: ["Versendet", "Sent"],
  archived: ["Archiviert", "Archived"],
  hold: ["Vorgemerkt", "On hold"],
  reserved: ["Reserviert", "Reserved"],
  expired: ["Abgelaufen", "Expired"],
  cancelled: ["Storniert", "Cancelled"],
  critical: ["Kritisch", "Critical"],
  warning: ["Prüfung erforderlich", "Review required"],
  info: ["Hinweis", "Information"],
};

export function propertyPresentationLabel(value: string, language: string) {
  return labels[value]?.[language === "de" ? 0 : 1] ?? value;
}

export function getPropertyWorkspaceCopy(language: string) {
  return language === "de" ? {
    navigation: "Immobilien-Bereiche", jump: "Bereich auswählen",
    inventory: "Bestandskennzahlen anzeigen", list: "Objektliste", details: "Objektdetails",
    viewDetails: "Details öffnen", back: "Zur Objektliste",
    resultCount: (count: number) => `${count} Einträge in dieser Ansicht`,
    noInventory: "Noch keine Immobilien in diesem Projektbereich.",
    noInventoryHint: "Legen Sie ein neues Objekt an oder wählen Sie ein anderes Projekt.",
    noResults: "Keine Treffer für diese Suche oder diesen Status.",
    noResultsHint: "Setzen Sie die Filter zurück oder passen Sie den Suchbegriff an.",
    noProjects: "Keine Projekte in diesem Bereich. Wählen Sie ein anderes Projekt oder legen Sie über „Weitere Aktionen“ ein Projekt an.",
    noReservations: "Keine aktiven Reservierungen in diesem Bereich.",
    noQuality: "Keine Auffälligkeiten in den geladenen Daten gefunden. Das ist keine Veröffentlichungsfreigabe.",
    noActivity: "Noch keine Anfrage- oder Reservierungsaktivitäten in diesem Bereich.",
    activityHint: "Diese Ansicht fasst Anfragen und aktive Reservierungen zusammen. Sie ist kein vollständiges Änderungsprotokoll.",
    requiredHint: "Pflichtfelder sind mit * markiert. Beträge in Euro; Flächen in m².",
    noProjectsCreate: "Für die Anlage ist ein Projekt erforderlich. Wählen Sie ein Projekt mit Bearbeitungsrechten oder legen Sie eines an.",
    preflight: "Vorprüfung", channel: "Kanal für die Vorprüfung",
    chooseTarget: "Anderes Objekt auswählen", target: "Objekt für Dokumente und Vermarktung",
    tableHint: "Die Tabelle kann bei Bedarf horizontal gescrollt werden.",
    imagePreview: "Bildvorschau", noPreview: "Keine Bildvorschau verfügbar",
    mediaHeading: "Bilder und Medien", documentsHeading: "Dokumente",
  } : {
    navigation: "Property sections", jump: "Select section",
    inventory: "Show inventory metrics", list: "Property list", details: "Property details",
    viewDetails: "Open details", back: "Back to property list",
    resultCount: (count: number) => `${count} entries in this view`,
    noInventory: "No properties in this project scope yet.",
    noInventoryHint: "Create a property or select another project.",
    noResults: "No results for this search or status.",
    noResultsHint: "Reset the filters or change your search.",
    noProjects: "No projects in this scope. Select another project or create one under “More actions”.",
    noReservations: "No active reservations in this scope.",
    noQuality: "No issues found in the loaded data. This is not a publication approval.",
    noActivity: "No inquiry or reservation activity in this scope yet.",
    activityHint: "This view summarizes inquiries and active reservations. It is not a complete change log.",
    requiredHint: "Required fields are marked *. Amounts are in euros; areas in m².",
    noProjectsCreate: "A project is required. Select a project you can edit or create one.",
    preflight: "Preflight", channel: "Channel for preflight",
    chooseTarget: "Select another property", target: "Property for documents and marketing",
    tableHint: "The table can be scrolled horizontally if needed.",
    imagePreview: "Image preview", noPreview: "No image preview available",
    mediaHeading: "Images and media", documentsHeading: "Documents",
  };
}
