version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    groups:
      production-security:
        dependency-type: production
        update-types:
          - patch
          - minor
    labels:
      - dependencies
      - security
